### ISSUE TITLE
google-cloud-run, ContainerOverride is missing command

### ISSUE THREAD

**Issue by iuiu34** [googleapis/google-cloud-python#12760] opened 2024-05-30 18:30 UTC
Hi,
in cloudRun. Given a job, you can override args but not command. Why?
I'm reporting this as bug, instead of feature requests, cause seems inconsistent to me

```
from google.cloud import run_v2

def run_job(command: str ,
            args: dict ,
            job_name: str ,
            location: str ,
            project: str 

            ):
    if type(args) is dict:
        args = [f'--{k}={v}' for k, v in args.items()]

    client = run_v2.JobsClient()
    args =['get_circ_mrna', '--args', 'args']
    container_overrides = run_v2.RunJobRequest.Overrides.ContainerOverride(
        args=args,
        # command=command # why this is not allowed?
    )

    overrides = run_v2.RunJobRequest.Overrides(
        container_overrides=[container_overrides]
    )
    job_name_ = f"projects/{project}/locations/{location}/jobs/{job_name}"

    request = run_v2.RunJobRequest(
        name=job_name_,
        overrides=overrides,
    )

    request = client.run_job(request=request)
    name = request.metadata.name.split('/')[-1]

    print(f"executed job: {name}")
    # response = operation.result()
    link = f"https://console.cloud.google.com/run/jobs/executions/details/{location}/{name}/tasks?project={project}"
    print(f"job link: {link}")
```

**Comment by iuiu34** [comment] 2024-05-30 18:44
@mukund-ananthu i don't follow

cloud run is in https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-run. 
Which is this current repo, where i'm opening the issue, no?

**Comment by parthea** [comment] 2024-05-30 18:47
@iuiu34 The issue is in the correct repository now.

**Comment by parthea** [comment] 2024-05-30 18:50
@iuiu34,
Regrettably, the feature doesn't exist in the Cloud Run API as per the [API documentation](https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.jobs/run#containeroverride). Thank you for [filing an issue](https://issuetracker.google.com/issues/343734020) in the API specific issue tracker. Please follow up via the API specific bug https://issuetracker.google.com/issues/343734020.

**Comment by iuiu34** [comment] 2024-05-30 18:53
understood.

For me is inconsistent also that is in the `cmd` but not in the python api

**Comment by parthea** [comment] 2024-08-26 14:49
I'm going to close this issue as the feature request is for the API itself rather than the client library. As per https://github.com/googleapis/google-cloud-python/issues/12760#issuecomment-2140682487, please follow up in the API specific issue tracker : https://issuetracker.google.com/issues/343734020

**Closed by parthea** 2024-08-26 14:49 UTC
Labels: type: feature request, api: pubsub, priority: p2, external
