### ISSUE TITLE
Cloudrun Domain Mapping API

### ISSUE THREAD

**Issue by arvindwill** [googleapis/google-cloud-python#10493] opened 2020-09-26 19:22 UTC
Is it possible to use this library to create Cloudrun Doman Mapping? 
![image](https://user-images.githubusercontent.com/2239985/94348578-0e7c8e80-005b-11eb-8cb5-0d57d9adce00.png)

If yes, is there a sample/demo script to explain how to perform it?

**Comment by busunkim96** [comment] 2020-09-28 15:57
Duplicate of https://github.com/googleapis/google-api-python-client/issues/1048. Closing.

**Closed by busunkim96** 2020-09-28 15:57 UTC
Labels: triage me
