### ISSUE TITLE
Autodetect not detecting header names when skip_leading_rows > 0

### ISSUE THREAD

**Issue by CharanVuda** [googleapis/google-cloud-python#10549] opened 2021-06-04 07:40 UTC
I am trying to create an external table on top of CSV file in GCS bucket. The file has 18 source system records followed by the actual header and then the data. When I use the below configuration, the header is coming as string_field_1, int64_field_2 but not the actual values in header record. Can you please help. Here is the code 

from google.cloud import bigquery
bq_client = bigquery.Client()
bq_dataset = 'mydataset'
dataset_ref         = bq_client.get_dataset(bq_dataset)
table_ref           = bigquery.TableReference(dataset_ref,'mytablename')
table               = bigquery.Table(table_ref) 
external_config     = bigquery.ExternalConfig('CSV')
external_config.autodetect              = True
external_config.source_uris             = 'gs:/mybucket/*'
external_config.options.field_delimiter = '|'
external_config.options.skip_leading_rows  = 18
external_config.options.allow_jagged_rows = False
external_config.max_bad_records         = 1
hive_part_options                       = bigquery.external_config.HivePartitioningOptions()
hive_part_options.mode                  = 'CUSTOM'
hive_part_options.source_uri_prefix     = 'gs:/mybucket/{hours_id:INTEGER}'
external_config.hive_partitioning       = hive_part_options 
table.external_data_configuration       = external_config
bq_client.create_table(table)

**Comment by parthea** [comment] 2021-06-04 12:06
Hi @CharanVuda,

To increase visibility, please can you file a bug [here](https://github.com/googleapis/python-bigquery/issues/new?assignees=&labels=&template=bug_report.md) in the [repository](https://github.com/googleapis/python-bigquery) for the `google-cloud-bigquery`package?

**Comment by CharanVuda** [comment] 2021-06-04 14:01
Created in the other repo. https://github.com/googleapis/python-bigquery/issues/687 -- For reference

**Comment by parthea** [comment] 2021-06-06 07:31
Hi @CharanVuda , I'm going to close this as duplicate of https://github.com/googleapis/python-bigquery/issues/687 as the issue has been assigned.

**Closed by parthea** 2021-06-06 07:31 UTC
Labels: triage me
