### ISSUE TITLE
Speech: Top alternative does not contain a words list for interim results when speaker diarization is enabled

### ISSUE THREAD

**Issue by jwinzer** [googleapis/google-cloud-python#9509] opened 2019-10-21 18:58 UTC
google-cloud-speech 1.2.0 Beta
Python 3.5

With `streaming_recognize`, `interim_results=True` and `enable_speaker_diarization=True` I expect to get a WordInfo list for the top alternative for every recognition result. However, I only get a word list for the final result and **not for interim results**.

```python
from google.cloud.speech_v1 import enums
from google.cloud.speech_v1 import SpeechClient
from google.cloud.speech_v1 import types
client = SpeechClient()
config = types.StreamingRecognitionConfig(
    config=types.RecognitionConfig(
        enable_speaker_diarization=True, ...
    ),
    interim_results=True
)
request = types.StreamingRecognizeRequest(audio_content=b'...')
requests = [request]
for response in client.streaming_recognize(config, requests):
    if response.results:
        result = response.result[0]
        if result.alternatives:
            alternative = result.alternative[0]
            if alternative.words:
                print(result.is_final)
```

**Comment by tseaver** [comment] 2019-10-22 18:53
FWIW, the [docs for the `interim_results` field of `StreamingRecognitionConfig` message](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1p1beta1#google.cloud.speech.v1p1beta1.StreamingRecognitionConfig) say:

> Optional If true, interim results (tentative hypotheses) may be returned as they become available (these interim results are indicated with the is_final=false flag). If false or omitted, only is_final=true result(s) are returned.

Note the word `may` there.

**Comment by tseaver** [comment] 2019-10-22 18:54
@beccasaurus Can you please elaborate?

**Comment by jwinzer** [comment] 2019-10-23 10:48
I do get result.alternative[0] with result.is_final being False. alternative.transcript is available. However, len(alternative.words) is 0, i.e. there is no word list for is_final False.

**Comment by jwinzer** [comment] 2019-10-25 14:57
@tseaver Could it be that the Google Speech server is only providing the word list for the _final result_? Is there a way to trace the messages received by gRPC to see if the word list is included?

**Comment by tseaver** [comment] 2019-10-25 15:13
@jwinzer Looking at the `streaming_recognize` implementation, https://github.com/googleapis/google-cloud-python/blob/35ba04617fdac125089539c4f3c8766605f8483b/speech/google/cloud/speech_v1/gapic/speech_client.py#L352-L412

that code doesn't do anything to morph the protobuf messages returned by the back-end.

**Comment by beccasaurus** [comment] 2019-10-25 16:43
I'm not certain if this is by design or not, but sounds like it's purely backend (not Python library)

It might be a question best posed to the backend API folks via the API's Issue Tracker:
https://cloud.google.com/speech-to-text/docs/getting-support#file_bugs_or_feature_requests

/cc @lwander @nnegrey who may know more about this scenario (Interim Results + Diarization)

**Comment by lwander** [comment] 2019-10-25 16:53
Do you get interim results without diarization enabled?

**Comment by jwinzer** [comment] 2019-10-25 21:14
To clarify I get interim results whether or not diarization is enabled. But I don't get a word list for interim results.

With enable_word_time_offsets I have the same scenario. I get a word list with time offsets for final results but no word list for interim results.

I have a feeling it is a backend issue.

**Comment by jwinzer** [comment] 2019-10-29 13:17
I created an issue for the backend folks: https://issuetracker.google.com/issues/143468770

**Comment by tseaver** [comment] 2019-10-29 19:19
@jwinzer Thanks for posting that issue link.  I'm going to close this issue, as I don't think there is anything to be done in the `google-cloud-speech` client library to address it.

**Closed by tseaver** 2019-10-29 19:19 UTC
Labels: api: speech, backend, type: question
