### ISSUE TITLE
bypass wafa

### ISSUE THREAD

**Issue by nottyboi513** [googleapis/google-cloud-python#10429] opened 2020-05-13 09:13 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by plamut** [comment] 2020-05-13 13:42
@nottyboi513 It is not clear what the issue is about, could you please clarify?

Thanks!

**Comment by busunkim96** [comment] 2020-05-15 19:48
Closing as it's unclear what the question is. Feel free to open a new issue with more details!

**Closed by busunkim96** 2020-05-15 19:48 UTC
Labels: type: question
