### ISSUE TITLE
Client libraries need out-of-band tests against prereleases of third party dependencies

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#10578] opened 2021-08-17 18:51 UTC
/cc @busunkim96, @tswast, @crwilcox 

I had originally worked to add `--pre` to the `testing/constraints-3.9.txt` files of the "manual" libraries:
- https://github.com/googleapis/python-api-core/pull/247
- https://github.com/googleapis/python-cloud-core/pull/129
- https://github.com/googleapis/google-resumable-media-python/pull/250
- https://github.com/googleapis/python-firestore/pull/415
- https://github.com/googleapis/python-bigtable/pull/402
- https://github.com/googleapis/python-datastore/pull/207
- https://github.com/googleapis/python-storage/pull/534
- https://github.com/googleapis/python-spanner/pull/479

However, in today's meeting the consensus was that such testing needs to happend out-of-band from the normal PR presubmit testing.  I have therefore reverted the already-merged PRs which had only that change:
- https://github.com/googleapis/python-firestore/pull/426
- https://github.com/googleapis/python-bigtable/pull/406
- https://github.com/googleapis/python-datastore/pull/213

For the already-merged PRs which contained more changes, I have created PRs which back out only the constraint change:
- https://github.com/googleapis/python-cloud-core/pull/132
- https://github.com/googleapis/python-spanner/pull/527

For the not-yet-merged PRs, I have backed out the constraint change, and re-titled them to signal the remaining changes:
- https://github.com/googleapis/python-api-core/pull/247
- https://github.com/googleapis/google-resumable-media-python/pull/250
- https://github.com/googleapis/python-storage/pull/534

Going forward, we need to work out how to do this testing out-of-band.
- https://github.com/googleapis/python-bigquery/pull/449 added a `prerelease_deps` session to `noxfile.py` (not run by default, because `noxfile.py` lists [explicit default sessions](https://github.com/tswast/python-bigquery/blob/97eb986001b2fbe13b3ffcbf1a8241e1302f2948/noxfile.py#L33-L45)  That PR sets up a separate `presubmit` job to run that specific `nox` session.
- Should we instead run such tests in nightly (`continuous`) builds?

**Comment by tswast** [comment] 2021-08-17 19:14
I've filed https://github.com/googleapis/python-bigquery/issues/882 to add a continuous build for BigQuery.

**Comment by tswast** [comment] 2021-11-29 20:03
Does `--pre` in the constraints file do what we want? I'd be more comfortable with that approach if we also had a line to log the version like we have in bigquery. e.g. `session.run("python", "-c", "import grpc; print(grpc.__version__)")`

Also:

* There are some packages like pandas and pyarrow which publish their pre-releases to a separate index. These need to be installed separately.
* We usually specify a top bound to our dependencies, but pre-release versions might be outside those bounds. `pip` will happily install a non-prerelease version rather than the latest pre-release version to be within those bounds. (We worked around this by using `--no-deps` in the bigquery session.

**Comment by parthea** [comment] 2022-06-10 15:30
Closing as duplicate of https://github.com/googleapis/synthtool/issues/1290

**Closed by parthea** 2022-06-10 15:30 UTC
Labels: type: process
