### ISSUE TITLE
better proxy support for users in China?

### ISSUE THREAD

**Issue by jl-DaDar** [googleapis/google-cloud-python#5348] opened 2018-05-19 04:40 UTC
I am trying to access google cloud services in China, and it is very painful to do so at the moment.
right now I am using REST with requests.get/post with proxy but I have to manually reconstruct the REST request. I can't change the global proxy env setting as I have other local Chinese services to call. 
Can you please add proxy support into the python google cloud client? 

Thanks.

**Comment by mitsuo0114** [comment] 2021-09-01 00:26
I'm also experiencing this. To change proxy setting, we need to change global proxy env. That affect to other threads and it is painful for me too.

Actually, another python library[1] allows us to use local proxy with configuring `httplib2`.
The maintainers of [1] recommend us to use this `google-cloud-python` in Readme. But this is the one of the biggest issue and we cannot migrate actually.

I hope team will handle this issue.

[1] https://github.com/googleapis/google-api-python-client

**Comment by parthea** [comment] 2023-10-21 20:19
Closing as a duplicate of https://github.com/googleapis/google-cloud-python/issues/10585

**Closed by parthea** 2023-10-21 20:19 UTC
Labels: type: feature request, api: core
