### ISSUE TITLE
Firestore: Upgrading google-cloud-firestore from 1.4.0 to 1.5.0 breaks autocomplete in IDEs

### ISSUE THREAD

**Issue by mr-bjerre** [googleapis/google-cloud-python#9601] opened 2019-11-05 13:35 UTC
#### Environment details

1. API: Firestore
2. macOS Mojave, version 10.14.6
3. Python 3.7.4
4. google-cloud-firestore version:  1.5.0

#### Steps to reproduce

Using PyCharm Pro 2019.2.4 I get no auto complete suggestions on `CollectionReference` object (and probably more) when upgrading `google-cloud-firestore` from `1.4.0` to `1.5.0`. The autocomplete does work on `Client` object though.

**Comment by tseaver** [comment] 2019-11-05 18:27
@mr-bjerre Can you please show how you import / reference `CollectionReference`?

**Comment by tseaver** [comment] 2019-11-05 19:02
E.g., all the expected "help" information is present in the following example:

```python
>>> from google.cloud.firestore_v1 import __version__
>>> __version__
'1.5.0'
>>> from google.cloud.firestore_v1 import collection
>>> help(collection.CollectionReference
```

**Comment by mr-bjerre** [comment] 2019-11-05 19:17
Here is an image using `v1.5.0`

<img width="551" alt="Screenshot 2019-11-05 at 20 12 39" src="https://user-images.githubusercontent.com/16841792/68238125-cdc1f400-0008-11ea-91e3-5fa11b77f384.png">

And a similar image for `v1.4.0`

<img width="658" alt="Screenshot 2019-11-05 at 20 13 33" src="https://user-images.githubusercontent.com/16841792/68238177-f0540d00-0008-11ea-8078-736303aac976.png">

Running `help(db.collection('john'))` does however give me the docs in both versions

```python
> help(db.collection('john'))

Help on CollectionReference in module google.cloud.firestore_v1.collection object:
class CollectionReference(builtins.object)
 |  CollectionReference(*path, **kwargs)
 |  .
 |  .
 |  .
```

**Comment by tseaver** [comment] 2019-11-05 19:39
Hmm, I can't see any difference in the `__doc__` between the two versions:

### 1.4.0
```python
>>> from google.cloud.firestore_v1 import __version__, client
>>> print(__version__)
1.4.0
>>> print(client.Client.collection.__doc__)
Get a reference to a collection.

        For a top-level collection:

        .. code-block:: python

            >>> client.collection('top')

        For a sub-collection:

        .. code-block:: python

            >>> client.collection('mydocs/doc/subcol')
            >>> # is the same as
            >>> client.collection('mydocs', 'doc', 'subcol')

        Sub-collections can be nested deeper in a similar fashion.

        Args:
            collection_path (Tuple[str, ...]): Can either be

                * A single ``/``-delimited path to a collection
                * A tuple of collection path segments

        Returns:
            :class:`~google.cloud.firestore_v1.collection.CollectionReference`:
            A reference to a collection in the Firestore database.
        
>>> 
```

### 1.5.0
```
>>> from google.cloud.firestore_v1 import __version__, client
>>> print(__version__)
1.5.0
>>> print(client.Client.collection.__doc__)
Get a reference to a collection.

        For a top-level collection:

        .. code-block:: python

            >>> client.collection('top')

        For a sub-collection:

        .. code-block:: python

            >>> client.collection('mydocs/doc/subcol')
            >>> # is the same as
            >>> client.collection('mydocs', 'doc', 'subcol')

        Sub-collections can be nested deeper in a similar fashion.

        Args:
            collection_path (Tuple[str, ...]): Can either be

                * A single ``/``-delimited path to a collection
                * A tuple of collection path segments

        Returns:
            :class:`~google.cloud.firestore_v1.collection.CollectionReference`:
            A reference to a collection in the Firestore database.
        
>>> 
```

**Comment by mr-bjerre** [comment] 2019-11-05 19:41
It might be related to this? https://github.com/googleapis/google-cloud-python/issues/8035

**Comment by tseaver** [comment] 2019-11-05 19:47
@mr-bjerre The fix for #8035 was merged in PR #8102, which was released in [`google-cloud-firestore-1.3.0`](https://github.com/googleapis/google-cloud-python/releases/tag/firestore-1.3.0).

Both the 1.4.0 and 1.5.0 versions have the same text for the `Returns:` field for `Client.connection`.

**Comment by mr-bjerre** [comment] 2019-11-05 19:49
Well then I can’t say what’s causing the issue. But I can conclude that it
works in 1.4.0 and not 1.5.0.

tir. 5. nov. 2019 kl. 20.47 skrev Tres Seaver <notifications@github.com>:

**Comment by mr-bjerre** [comment] 2019-11-05 20:48
Let me know if there is anything else I can do

**Comment by tseaver** [comment] 2019-11-05 21:14
@mr-bjerre I'm going to need more info on reproducing the issue in "pristine" virtual environments.  E.g.:

### Create virtualenv for 1.4.0
```bash
$ python3.7 -m venv /tmp/gcp/9601/firestore-1.4.0
$ /tmp/gcp/9601/firestore-1.4.0/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.3.1 setuptools-41.6.0 wheel-0.33.6
$ /tmp/gcp/9601/firestore-1.4.0/bin/pip install google-cloud-firestore==1.4.0
...
Successfully installed cachetools-3.1.1 certifi-2019.9.11 chardet-3.0.4 google-api-core-1.14.3 google-auth-1.7.0 google-cloud-core-1.0.3 google-cloud-firestore-1.4.0 googleapis-common-protos-1.6.0 grpcio-1.24.3 idna-2.8 protobuf-3.10.0 pyasn1-0.4.7 pyasn1-modules-0.2.7 pytz-2019.3 requests-2.22.0 rsa-4.0 six-1.13.0 urllib3-1.25.6
```

### Create virtualenv for 1.4.0
```bash
$ python3.7 -m venv /tmp/gcp/9601/firestore-1.5.0
$ /tmp/gcp/9601/firestore-1.5.0/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.3.1 setuptools-41.6.0 wheel-0.33.6
$ /tmp/gcp/9601/firestore-1.5.0/bin/pip install google-cloud-firestore==1.5.0
...
Successfully installed cachetools-3.1.1 certifi-2019.9.11 chardet-3.0.4 google-api-core-1.14.3 google-auth-1.7.0 google-cloud-core-1.0.3 google-cloud-firestore-1.5.0 googleapis-common-protos-1.6.0 grpcio-1.24.3 idna-2.8 protobuf-3.10.0 pyasn1-0.4.7 pyasn1-modules-0.2.7 pytz-2019.3 requests-2.22.0 rsa-4.0 six-1.13.0 urllib3-1.25.6
```

If you cannot reproduce the issue in the fresh virtualenv, then maybe look at the output of `pip list` in the two environments you used to reproduce the example in the IDE GUI above?

BTW, what IDE are you using?

**Comment by mr-bjerre** [comment] 2019-11-05 21:26
Using **PyCharm Pro 2019.2.4** as stated in first comment. Thats why I suspected #8035 to be related - but I suppose it can't be related since it's working in 1.4.0.

```
(venv1.4) ➜  pip list
Package                  Version  
------------------------ ---------
cachetools               3.1.1    
certifi                  2019.9.11
chardet                  3.0.4    
google-api-core          1.14.3   
google-auth              1.7.0    
google-cloud-core        1.0.3    
google-cloud-firestore   1.4.0    
googleapis-common-protos 1.6.0    
grpcio                   1.24.3   
idna                     2.8      
pip                      19.0.3   
protobuf                 3.10.0   
pyasn1                   0.4.7    
pyasn1-modules           0.2.7    
pytz                     2019.3   
requests                 2.22.0   
rsa                      4.0      
setuptools               40.8.0   
six                      1.13.0   
urllib3                  1.25.6   
```

```
(venv1.5) ➜  pip list                                 
Package                  Version  
------------------------ ---------
cachetools               3.1.1    
certifi                  2019.9.11
chardet                  3.0.4    
google-api-core          1.14.3   
google-auth              1.7.0    
google-cloud-core        1.0.3    
google-cloud-firestore   1.5.0    
googleapis-common-protos 1.6.0    
grpcio                   1.24.3   
idna                     2.8      
pip                      19.0.3   
protobuf                 3.10.0   
pyasn1                   0.4.7    
pyasn1-modules           0.2.7    
pytz                     2019.3   
requests                 2.22.0   
rsa                      4.0      
setuptools               40.8.0   
six                      1.13.0   
urllib3                  1.25.6   
```

**Comment by tseaver** [comment] 2019-11-06 15:41
I just installed PyCharm-Community 2019.2.4, and used it to create a project with firestore-1.4.0.  When I updated the firestore version within that same project to 1.5.0, I could reproduce your report, until I poked a bit at the console, at which point the completion began working again.

I installed firestore 1.5.0 in a fresh project, and the completion worked perfectly (see attached image).

![Screenshot from 2019-11-06 10-40-53](https://user-images.githubusercontent.com/242750/68313064-fb974f00-0081-11ea-8c95-6e41d86fcf3d.png)


At this point, I'm going to close this as related to how PyCharm is interacting with cached files in its virtual environment, rather than any issue with the google-cloud-firestore 1.5.0 release itself.  Please feel free to follow up if you can provide more information.

**Closed by tseaver** 2019-11-06 15:41 UTC
Labels: api: firestore, status: awaiting information, type: question
