### ISSUE TITLE
Importing google.cloud.logging.Client adds StreamHandler to root

### ISSUE THREAD

**Issue by hnykda** [googleapis/google-cloud-python#6477] opened 2018-11-12 09:57 UTC
Importing a google cloud logging Client adds a handler to the root logger. That's IMO unexpected and may break users code. Imports *must not* have any side-effects. 

A real-life example when it broke our code: our library has something like:
```
if logger.hasHandlers():
  initialize_logging()
```
but because we imported the Client somewhere on the beginning of the module, this didn't get executed. 

#### Environment details
`Python 3.7.0`, docker image `python:3.7-slim`

#### Steps to reproduce

1. `docker run -ti python:3.7-slim bash`
2. `pip install google-cloud-logging=1.8.0`
3. `python`:
```
root@45804a66c8d3:/# python
>>> import logging
>>> logging.root.handlers
[]
>>> from google.cloud.logging import Client
>>> logging.root.handlers
[<StreamHandler <stderr> (NOTSET)>]
```

**Comment by tseaver** [comment] 2018-11-12 17:03
@hnykda The `google-cloud-logging` library does not itself add any handlers unless you call its `setup_logging` utility function.  I believe that the issue is actually with the `grpcio` package, which has merged PRs to fix the issue:

- `master` branch: https://github.com/grpc/grpc/pull/17064
- `1.16` branch: https://github.com/grpc/grpc/pull/17091

I don't believe either of those fixes is available yet in a release.

**Closed by tseaver** 2018-11-12 17:03 UTC
Labels: api: logging, type: question

**Comment by tseaver** [comment] 2018-11-12 17:05
Looks like https://pypi.org/project/grpcio/1.16.1rc1/ contains the fix.  You can upgrade to it via:

```bash
$ /path/to/venv/bin/pip install --upgrade grpcio==1.16.1rc1
```

**Comment by hnykda** [comment] 2018-11-12 17:07
Thanks for a quick resolution :+1:
