### ISSUE TITLE
Get Docker Image size in GAR

### ISSUE THREAD

**Issue by ruodingt** [googleapis/google-cloud-python#11436] opened 2023-06-27 05:18 UTC
Hi team,

I am trying to use python client to fetch metadata (like image size) of a docker images with `arc.get_docker_image`. 

- I am not sure whether it is the right approach
- I wonder whether there is any other alternatives to get image size since the code below does not work well.

I am expecting the following code could work:

```
from google.cloud.artifactregistry import ArtifactRegistryClient, ListTagsRequest, ListPackagesRequest, Package, GetDockerImageRequest

src_img = f'{loc}-docker.pkg.dev/{proj}/{repo_src}/{pn}:{tag_name}' 

# src_img looks like `australia-southeast1-docker.pkg.dev/kkk-x-xxx-build-prod-xxxxxx/docker-registry-repository/abc-pipeline-flex:latest`
gir = GetDockerImageRequest(dict(name=src_img))
dkim = arc.get_docker_image(name=src_img)

```

However I got error:

```
google.api_core.exceptions.InvalidArgument: 400 Invalid resource field value in the request. [reason: "RESOURCE_PROJECT_INVALID"
domain: "googleapis.com"
metadata {
  key: "method"
  value: "google.devtools.artifactregistry.v1.ArtifactRegistry.GetDockerImage"
}
metadata {
  key: "service"
  value: "artifactregistry.googleapis.com"
}
]
```

Please give me some idea how to fetch the image size with program.

**Comment by parthea** [comment] 2023-07-06 19:22
I was not able to re-create the error. See example below to list all repositories, all images and their corresponding size.


```
from google.cloud.artifactregistry import ArtifactRegistryClient, ListRepositoriesRequest

project = "<YOUR PROJECT>"
location = "<YOUR LOCATION>"
arc = ArtifactRegistryClient()

request = ListRepositoriesRequest(
    parent=f"projects/{project}/locations/{location}",
)

# Make the request to list artifact registry repositories
paged_result = arc.list_repositories(request=request)

for repository in paged_result:
    # Get docker images for each repository
    images = arc.list_docker_images(parent=repository.name)

    for image in images:
        # For each image, get the size
        image_details = arc.get_docker_image(name=image.name)
        print(f"name: {image.name} size: {image_details.image_size_bytes}")
```

**Comment by parthea** [comment] 2023-07-07 19:53
I'm going to close this issue but please feel free to open a new issue if you have additional questions.

**Closed by parthea** 2023-07-07 19:53 UTC
Labels: type: question, api: artifactregistry

**Comment by glasser** [comment] 2023-12-09 05:57
I ran into this same error with the NodeJS client. The issue is that this API requires you to pass in `name` in the form `projects/kkk-x-xxx-build-prod-xxxxxx/locations/australia-southeast1/repositories/docker-registry-repository/dockerImages/abc-pipeline-flex@sha256:2dd6956aa4f462badb7aa445f73092b19e55e2be2c03bee4ec230700963b3f55` rather than the form you use the repository with Docker.

In addition, as far as I can tell, it *only* lets you pass in the sha, not a tag. If you want to look up by tag you have to use the completely separate `get_tag` API, like `arc.get_tag(name='projects/kkk-x-xxx-build-prod-xxxxxx/locations/australia-southeast1/repositories/docker-registry-repository/packages/abc-pipeline-flex/tags/latest')`, which will give you back and object with a "version" that you then need extract the SHA from in order to pass to get_docker_image in the format above.

**Comment by StevenACoffman** [comment] 2024-02-03 17:58
@glasser Thanks! I used your comment above and managed to stumble through this awkward situation using the Go SDK. I eventually added to our internal documentation:

+ `GetDockerImage` RPC API requires you to pass in a Name in the format `projects/%s/locations/%s/repositories/%s/packages/%s@%s`. For example:
  ```
  projects/gcp-project/locations/us-central1/repositories/myrepo/packages/myapp@sha256:2dd6956aa4f462badb7aa445f73092b19e55e2be2c03bee4ec230700963b3f55
  ```
+ `ListDockerImages` RPC API wants Name in the format `projects/%s/locations/%s/repositories/%s`, for example:
  ```
  projects/gcp-project/locations/us-central1/repositories/myrepo
  ```
+ `GetTag` RPC API wants Name in the format `projects/%s/locations/%s/repositories/%s/packages/%s/tags/%s`, for example:
  ```
  projects/gcp-project/locations/us-central1/repositories/myrepo/packages/myapp:mytag
  ```
If you have a Docker URL but don't have the Docker SHA256, you can use `GetTag` and from that response extract the Version. Then you can pass that SHA256 to `GetDockerImage`.

**Comment by CMorton737** [comment] 2024-06-20 19:44
> * ```
>   projects/gcp-project/locations/us-central1/repositories/myrepo/packages/myapp@sha256:2dd6956aa4f462badb7aa445f73092b19e55e2be2c03bee4ec230700963b3f55
>   ```

I've found that GetDockerImage RPC API actually requires the name format to be 
`projects/gcp-project/locations/us-central1/repositories/myrepo/dockerImages/myapp@sha256:2dd6956aa4f462badb7aa445f73092b19e55e2be2c03bee4ec230700963b3f55
`
