### ISSUE TITLE
Speech: 'SpeechClient.recognise' hangs

### ISSUE THREAD

**Issue by PietroPasotti** [googleapis/google-cloud-python#7214] opened 2019-01-28 13:20 UTC
Problem is: google.cloud speech services hangs whenever I make a recognition/synthesis request. Here I open the issue for recognition, but the exact same happens for texttospeech.TextToSpeechClient.

#### Environment details
On Windows 10 x64
Python 3.7.2
Pip freeze:

```
adal==1.2.0
aniso8601==4.1.0
apispec==0.39.0
asn1crypto==0.24.0
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.17
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-datalake-store==0.0.40
azure-eventgrid==1.2.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.0.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.4.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.6.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.2.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.5.1
azure-mgmt-notificationhubs==2.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.5.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.1.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.0.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
azure-storage-file==1.4.0
azure-storage-queue==1.4.0
cachetools==3.0.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
coreapi==2.3.3
coreschema==0.0.4
cryptography==2.5
DateTime==4.3
Django==2.1.5
django-rest-swagger==2.2.0
djangorestframework==3.9.1
Flask==1.0.2
flask-restplus==0.12.1
google-api-core==1.7.0
google-auth==1.6.2
google-cloud==0.34.0
google-cloud-speech==0.36.2
google-cloud-texttospeech==0.3.0
googleapis-common-protos==1.5.6
grpcio==1.18.0
idna==2.8
isodate==0.6.0
itsdangerous==1.1.0
itypes==1.1.0
Jinja2==2.10
jsonschema==2.6.0
MarkupSafe==1.1.0
marshmallow==2.18.0
msrest==0.6.4
msrestazure==0.6.0
oauthlib==3.0.0
openapi-codec==1.3.2
protobuf==3.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycparser==2.19
Pygments==2.3.1
PyJWT==1.7.1
python-dateutil==2.7.5
pytz==2018.9
PyYAML==3.13
requests==2.21.0
requests-oauthlib==1.2.0
rsa==4.0
simplejson==3.16.0
six==1.12.0
uritemplate==3.0.0
urllib3==1.24.1
webargs==5.1.0
Werkzeug==0.14.1
zope.interface==4.6.0
```

#### Steps to reproduce

 Create a service client instance, and invoke recognize. 

#### Code example

```
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types

client = speech.SpeechClient(credentials = <<MY CREDENTIALS>>)
audio = types.RecognitionAudio(content = <<MY BYTE OBJECT>>)
config = types.RecognitionConfig(language_code='en-US')
response = client.recognize(config, audio)
```

#### Stack trace

After waiting for 5+ minutes, I hit ctrl-c and get this stack:

```
In [40]: client.recognize(config,audio)
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-40-e7f5167558f9> in <module>
----> 1 client.recognize(config,audio)

~\code\speech\Lib\site-packages\google\cloud\speech_v1\gapic\speech_client.py in recognize(self, config, audio, retry, timeout, metadata)
    237         request = cloud_speech_pb2.RecognizeRequest(config=config, audio=audio)
    238         return self._inner_api_calls["recognize"](
--> 239             request, retry=retry, timeout=timeout, metadata=metadata
    240         )
    241

~\code\speech\Lib\site-packages\google\api_core\gapic_v1\method.py in __call__(self, *args, **kwargs)
    141             kwargs["metadata"] = metadata
    142
--> 143         return wrapped_func(*args, **kwargs)
    144
    145

~\code\speech\Lib\site-packages\google\api_core\retry.py in retry_wrapped_func(*args, **kwargs)
    268                 sleep_generator,
    269                 self._deadline,
--> 270                 on_error=on_error,
    271             )
    272

~\code\speech\Lib\site-packages\google\api_core\retry.py in retry_target(target, predicate, sleep_generator, deadline, on_error)
    203             "Retrying due to {}, sleeping {:.1f}s ...".format(last_exc, sleep)
    204         )
--> 205         time.sleep(sleep)
    206
    207     raise ValueError("Sleep generator stopped yielding sleep values.")

KeyboardInterrupt:
```

Thanks :)

**Comment by wofka72** [comment] 2019-04-09 20:04
I have the same problem.

**Comment by Cmotions-reader** [comment] 2019-05-10 07:40
I don't know if this is still relevant for you guys, but mayve it will help somebody in the future. I had the same issue on my RPI 3B+, OS = Raspbian, using Python3.
After trying different things I found out that the recognize function didn't respond because the credentials weren't passed in the right way to the SpeechClient function. I solved this by adding/changing my code in the following way:
`creds = service_account.Credentials.from_service_account_file("./path/credentials.json") speech_client = speech_v1.SpeechClient(credentials=creds)`

**Comment by sduskis** [comment] 2019-06-13 15:09
It seems like there were a number of issues here that all caused the same behavior:

1. using bad credentials can cause hanging behavior.  We know that this is a problem for all clients, but don't have a clean fix as of yet.
2. "Name resolution failure" is a networking issue.  The service URL could not be reached.
3. Possibly some other root cause.

At this point, there doesn't seem to be anything active we can do to fix these problems, so I'm going to close this bug.  If this happens again, please open a new issue.

**Closed by sduskis** 2019-06-13 15:09 UTC
Labels: api: speech, backend, type: question
