### ISSUE TITLE
Pub/Sub: receiver won't pull messages until client restart

### ISSUE THREAD

**Issue by arvindnrbt** [googleapis/google-cloud-python#7001] opened 2018-12-19 06:47 UTC
#### Environment details

1. (Dockerized) Alpine 3.7
2. python 3.5
3. google-cloud-pubsub - v.0.37.2

#### Steps to reproduce
This occurs frequently but the time it takes to stop listening is random, sometimes it has taken 3 hours and sometimes it takes about a week. The actual problem is the long running listener seems to quit after sometime and we need to manually restart the process.

  1. Start a pubsub listener as new multiprocessing process from a Django server.
  2. Publish a message and find that the subscriber's callback is not being invoked.
  3. It will not receive messages until the process is restarted again.

#### Code example
```python
# example
        flow_control = pubsub_v1.types.FlowControl(max_messages=10)
        op_future = (self.subscriber
                     .subscribe(self.subscription_name,
                                callback=self.callback,
                                flow_control=flow_control))
        log.info("Subscription started to %s", self.topic)
        try:
            op_future.result()
        except Exception as err:
            log.exception(err)
```

#### Logs
```
# example
There seems to be no useful log for this issue other than this from the subscriber since it is running in a multiprocess inside a docker container.

18-12-2018:13:56:39,543 INFO     [Thread-3] [streaming_pull_manager.py:447] Observed recoverable stream error 504 Deadline Exceeded
18-12-2018:13:56:39,543 INFO     [Thread-ConsumeBidirectionalStream] [streaming_pull_manager.py:447] Observed recoverable stream error 504 Deadline Exceeded
18-12-2018:13:56:39,546 INFO     [Thread-3] [bidi.py:367] Re-established stream
```

**Comment by sduskis** [comment] 2019-05-24 18:36
@plamut, this may be a duplicate, but it's worth looking at this.

**Comment by sduskis** [comment] 2019-06-04 16:09
@arvindnrbt  There were a number of fixes that may have corrected this issue.  Can you please upgrade the client and see if this issue is reproducible? 

I'm going to close this issue, since we can't do much at this point.  If this issue is indeed reproducible, please open a new issue.

**Closed by sduskis** 2019-06-04 16:09 UTC
Labels: api: pubsub, triaged for GA, type: question
