### ISSUE TITLE
BigQuery Data Transfer: schedule_transfer_runs invalid input type for start and end times

### ISSUE THREAD

**Issue by antonimaciej** [googleapis/google-cloud-python#7795] opened 2019-04-24 07:03 UTC
I am trying to use `gcp_bigquery_schedule_transfer_runs` method but I get `google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.`

Python client uses `google.protobuf.timestamp_pb2.Timestamp` objects as input parameters for start_time and end_time, where the api itself uses ISO 8601 datetime string. As can be checked [here](https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs/scheduleRuns)

I think there is a bug in convertion between those types.

This is the error message I get:
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "{"created":"@1556088650.615736900","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Request contains an invalid argument.","grpc_status":3}"
>
```

**Comment by antonimaciej** [comment] 2019-04-25 07:53
The code to reproduce my problem:

```
import datetime
from google.protobuf.timestamp_pb2 import Timestamp
from google.cloud.bigquery_datatransfer_v1 import DataTransferServiceClient

PROJECT_ID = 'project_id'
TRANSFER_CONFIG_ID = 'transfer_config_id'

start = datetime.datetime.now() + datetime.timedelta(hours=5)
end = datetime.datetime.now() + datetime.timedelta(days=5)

parent = 'projects/{}/transferConfigs/{}'.format(PROJECT_ID, TRANSFER_CONFIG_ID)
start_time = Timestamp(seconds=int(start.timestamp()))
end_time = Timestamp(seconds=int(end.timestamp()))

client = DataTransferServiceClient()

client.schedule_transfer_runs(
    parent=parent,
    start_time=start_time,
    end_time=end_time
)
```
To run this: change PROJECT_ID and TRANSFER_CONFIG_ID to valid ids and set GOOGLE_APPLICATION_CREDENTIALS enviroment variable

**Comment by tswast** [comment] 2019-04-25 15:43
Unfortunately "Request contains an invalid argument." can be caused by many different kinds of errors.

@antonimaciej can you run in [gRPC debug mode](https://stackoverflow.com/a/37125976/101923) and see if there are any hints as to the field name that is missing?

```
export GRPC_TRACE=all
export GRPC_VERBOSITY=DEBUG
```

Have you successfully made any calls to the BQ-DTS API using the service account at `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by mik-laj** [comment] 2019-04-26 12:41
I also encountered this problem. I send all other queries correctly using this library, but I could not correctly execute method - `schedule_transfer_runs`. Error messages are not descriptive, but this method takes only 3 parameters. One parameter is a constant text value. I copy it from from a request to REST. Other parameters take the Timestamp object. It is complex and poorly documented, so only it can cause problems.

I tried to debug using these methods, but I could not find any other reason.

I spent a lot of time trying to find the use of this library, but I am considering using this direct call to the REST API now. Old and good REST is a stable solution :-D Before choosing this solution, I sent a message to my POC on Google DTS Team. I hope that we will find a better solution.

**Comment by sgreenberg** [comment] 2019-12-13 23:15
I'm closing this out because it's old and the version of the library has bumped a few times between now and then. @tswast and I talked, and he suggested that the issue may be that `start` and `end` are not being parsed correctly as protobuff Timestamps. @antonimaciej - Please feel free to reopen if this is still causing you trouble.

**Closed by sgreenberg** 2019-12-13 23:15 UTC
Labels: api: bigquerydatatransfer, type: question
