### ISSUE TITLE
How to create documents with the discovery engine?

### ISSUE THREAD

**Issue by traed** [googleapis/google-cloud-python#12318] opened 2024-02-15 16:04 UTC
I'm trying to insert a document with the discoveryengine_v1 module I'm getting a generic "invalid argument" error with no way to see what the actual problem is... I'm running the following python function in a cloud function:

```
import json
import functions_framework
from google.cloud import discoveryengine_v1

@functions_framework.http
def run(request):
    request_json = request.get_json(silent=True)

    doc_json = {
        "title": request_json['title'],
        "body": request_json['body'],
        "categories": request_json['categories'],
        "uri": request_json['uri'],
    }

    document = discoveryengine_v1.Document()
    document.json_data = json.dumps(doc_json)

    client = discoveryengine_v1.DocumentServiceClient()
    request = discoveryengine_v1.CreateDocumentRequest(
        parent=request_json['name'],
        document_id=request_json['id'],
        document=document,
    )
    client.create_document(request=request)

    return "OK"
```

`client.create_document(request=request)` is the line causing the error according to the logs. The exact error being `google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.`. I have verified that the inputs are of the correct types as specified in the documentation so I don't see any reason for this. I have read through the docs but any examples there are pretty useless since they don't even include all the required parameters...

Can anyone please explain why this isn't working?

**Comment by parthea** [comment] 2024-02-27 13:19
Hi @traed,

Thanks for sharing a code snippet. The snippet appears to work using the test values below.

```
import json
from google.cloud import discoveryengine_v1


doc_json = {
    "title": "Test document title",
    "body": "Test document description",
    "categories": ["sports > clip","sports > highlight"],
    "uri": "http://www.example.com",
}

document = discoveryengine_v1.Document()
document.json_data = json.dumps(doc_json)

client = discoveryengine_v1.DocumentServiceClient()
request = discoveryengine_v1.CreateDocumentRequest(
    parent="projects/python-docs-samples-tests/locations/global/dataStores/<datastore>/branches/default_branch",
    document_id="id",
    document=document,
)
client.create_document(request=request)
```

I tried removing the `document_id` argument of `CreateDocumentRequest` as a test to check the error message and received the error message `google.api_core.exceptions.InvalidArgument: 400 Field "document_id" is a required field, but no value is found. [detail: "document_id"`. I would expect there should be more detail besides `400 Request contains an invalid argument`. Please can you check whether the following results in more detailed error messages?

- Upgrade `google-api-core` by running `pip install --upgrade google-api-core`
- Try using REST instead of gRPC in case the error message from REST is more detailed. As a quick check try using `client = discoveryengine_v1.DocumentServiceClient(transport="rest")` instead of `client = discoveryengine_v1.DocumentServiceClient()` 

Please let me know if the above steps help provide more error information.

**Comment by parthea** [comment] 2024-03-06 11:40
I'm going to close this issue as more information is needed to help troubleshoot but please feel free to open a new issue with more information.

**Closed by parthea** 2024-03-06 11:40 UTC
Labels: type: question, needs more info, api: discoveryengine

**Comment by softinio** [comment] 2024-04-03 18:43
I've hit the same problem. I wonder if it's something in the documents content causing this. 

Any ideas since last discussed? 

Thanks.

**Comment by parthea** [comment] 2024-04-03 18:45
@softinio Can you share a minimal reproduction?

**Comment by softinio** [comment] 2024-04-04 16:11
@parthea 

Code: 

```

    def upload_json_document(self, document: Dict):
        client = discoveryengine.DocumentServiceClient()

        parent = "projects/myproj/locations/global/datastores/guides_1/branches/default_branch"

        attachment = discoveryengine.Document(struct_data=document)

        print(f"attachment: {attachment}")

        request = discoveryengine.CreateDocumentRequest(
            parent=parent, document=attachment, document_id=str(document.get("id"))
        )

        print(f"request: {request}")

        operation = client.create_document(request=request)

        print(f"Waiting for operation to complete...{operation}")

        response = operation.result()

        # Handle the response
        print(response)
        return response

```

When running in repl showing dict I used, print statements for debugging and resulting error:

```

>>> testdict = { "id": "0855fb504869077cce7d2d06209f57df", "title":"Test document", "body":"document body"}
>>> d.upload_json_document(testdict)
attachment: struct_data {
  fields {
    key: "title"
    value {
      string_value: "Test document"
    }
  }
  fields {
    key: "id"
    value {
      string_value: "0855fb504869077cce7d2d06209f57df"
    }
  }
  fields {
    key: "body"
    value {
      string_value: "document body"
    }
  }
}

request: parent: "projects/myproj/locations/global/datastores/guides_1/branches/default_branch"
document {
  struct_data {
    fields {
      key: "title"
      value {
        string_value: "Test document"
      }
    }
    fields {
      key: "id"
      value {
        string_value: "0855fb504869077cce7d2d06209f57df"
      }
    }
    fields {
      key: "body"
      value {
        string_value: "document body"
      }
    }
  }
}
document_id: "0855fb504869077cce7d2d06209f57df"

Traceback (most recent call last):
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Request contains an invalid argument."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.191.42:443 {created_time:"2024-04-04T09:00:18.288019-07:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sr/Projects/chai/src/google/data_store.py", line 79, in upload_json_document
    operation = client.create_document(request=request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/google/cloud/discoveryengine_v1beta/services/document_service/client.py", line 1097, in create_document
    response = rpc(
               ^^^^
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sr/Projects/chai/.venv/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.
```
