### ISSUE TITLE
When updating a Job with same config, ERROR: Could not convert Any to Job

### ISSUE THREAD

**Issue by gabrielsicara** [googleapis/google-cloud-python#11868] opened 2023-10-12 08:14 UTC
#### Steps to reproduce

  1. Get an existing Job
  2. Update the job without any changes

#### Code example

```python
jobs_client = JobsClient()

get_job_request = GetJobRequest({"name": full_job_name})
job_to_update = jobs_client.get_job(request=get_job_request)

update_job_request = UpdateJobRequest(
      {
          "job": job_to_update,
      }
  )

operation = jobs_client.update_job(request=update_job_request)
```

#### Stack trace
```
TypeError: Could not convert Any to Job
```

**Comment by parthea** [comment] 2023-11-07 21:44
I'm not able to reproduce the issue. I created a job using the instructions [here](https://cloud.google.com/run/docs/quickstarts/jobs/create-execute#create_a_job) and I was able to execute the same code that you shared without modifications.

```
jobs_client = JobsClient()

get_job_request = GetJobRequest({"name": full_job_name})
job_to_update = jobs_client.get_job(request=get_job_request)

update_job_request = UpdateJobRequest(
      {
          "job": job_to_update,
      }
  )

operation = jobs_client.update_job(request=update_job_request)
```

I'm going to close this issue as not reproducible but please feel free to open a new issue with more information.

**Closed by parthea** 2023-11-07 21:44 UTC
Labels: api: run
