### ISSUE TITLE
Pubsub:  subscribing with Invalid JSON key hangs.

### ISSUE THREAD

**Issue by luxiangu** [googleapis/google-cloud-python#7587] opened 2019-03-27 19:50 UTC
Thanks for stopping by to let us know something could be better!

If you are still having issues, please be sure to include as much information as possible:

Issue Summary: 
We're following the example at [1], and we're running the test script with an invalid/deleted service account JSON key but the script would keep running indefinitely and never returns an auth exception.

[1] https://cloud.google.com/pubsub/docs/pull#listening-for-errors

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: Google Cloud Chell
3. Python version and virtual environment information: Python 2.7.13
4. google-cloud-<service> version:  google-cloud-pubsub-0.40.0

#### Steps to reproduce

  1. Try to run the following test script of async pull from a subscription with an service account Json key, then delete the key but it would never return any auth exception; however for sync pull from the subscription would throw auth exception after 10 mins which is expected: Deadline of 600.0s exceeded while calling <functools.partial object at 0x7f7767d04c00>, last exception: 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid JWT Signature.', u'{\n "error": "invalid_grant",\n "error_description": "Invalid JWT Signature."\n}')

#### Code example - Async

```python
import time
import json
from google.cloud import pubsub_v1
from google.oauth2 import service_account
from google.api_core.exceptions import NotFound

project_id = "PROEJCT_ID"
subscription_name = "SUBSCRIPTION_NAME"


def callback(message):
    print('Received message: {}'.format(message))
    print('Error? {}'.format(future.exception()))
    message.ack()

def sub_loop_contents():
    service_account_info = json.load(open('service_account_key.json'))
    credentials = service_account.Credentials.from_service_account_info(service_account_info)
    subscriber = pubsub_v1.SubscriberClient(credentials=credentials)
    # The `subscription_path` method creates a fully qualified identifier
    # in the form `projects/{project_id}/subscriptions/{subscription_name}`
    subscription_path = subscriber.subscription_path(project_id, subscription_name)

    print('Listening for messages on {}'.format(subscription_path))

    # NOTE. If we call this before the subscription is properly created, we will never get any messages.
    # This is why we need the subscription.get permission.
    future = subscriber.subscribe(subscription_path, callback=callback)

    try:
        # Block thread waiting for results.
        future.result()
    except Exception as e:
        print('Listening for messages on {} threw an Exception: {}.'.format(subscription_name, e))
        future.cancel()

if __name__ == '__main__':
    sub_loop_contents()

```

#### Stack trace
```
Nothing as it would just hang there
```
#### Code example - Sync
```python
import time
import json
from google.cloud import pubsub_v1
from google.oauth2 import service_account
from google.api_core.exceptions import NotFound


project_id = "PROJECT_ID"
subscription_name = "SUBSCRIPTION_NAME"



def sub_loop_contents():
 
    service_account_info = json.load(open('SERVICE_ACCOUNT_KEY.json'))
    credentials = service_account.Credentials.from_service_account_info(service_account_info)    
    subscriber = pubsub_v1.SubscriberClient(credentials=credentials)
    
    # The `subscription_path` method creates a fully qualified identifier
    # in the form `projects/{project_id}/subscriptions/{subscription_name}`
    subscription_path = subscriber.subscription_path(project_id, subscription_name)

    print('Listening for messages on {}'.format(subscription_path))
    


    # NOTE. If we call this before the subscription is properly created, we will never get any messages.
    # This is why we need the subscription.get permission.
    # future = subscriber.subscribe(subscription_path, callback=callback)
    
    while True:
        try:
            response = subscriber.pull(subscription_path, 100)
            print(response)
        except Exception as ex:
            print(ex)
            break


if __name__ == '__main__':
    
    sub_loop_contents()
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by matthewbest** [comment] 2019-04-01 14:20
I am also seeing the same behavior; looking forward to a bug fix as soon as possible.

**Comment by sduskis** [comment] 2019-06-11 13:12
This is a duplicate of #7199

**Closed by sduskis** 2019-06-11 13:12 UTC
Labels: api: pubsub, priority: p2, type: bug
