### ISSUE TITLE
PubSub: Add documentation for correct usage of SubscriberClient.streaming_pull

### ISSUE THREAD

**Issue by ostrokach** [googleapis/google-cloud-python#8555] opened 2019-07-02 00:06 UTC
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")

PubSub

2. OS type and version

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

3. Python version and virtual environment information: `python --version`

```bash
$ python --version
Python 3.6.8
```

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

```bash
$ pip show google-cloud-pubsub
Name: google-cloud-pubsub
Version: 0.42.1
Summary: Google Cloud Pub/Sub API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: google-api-core, grpc-google-iam-v1
Required-by: 
```

#### Code example

***See the following colab notebook***: https://colab.research.google.com/github/ostrokach/beam-notebooks/blob/master/notebooks/pubsub_streaming_pull.ipynb.

Basically, following the documented way of using `SubscriberClient.streaming_pull(...)` produces an error shown below. Googling around, it appears that the `requests=...` argument must actually be a generator of `pubsub.types.StreamingPullRequest` objects, rather than a list of dictionaries.

#### Stack trace

```python-traceback
Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 191, in consume_request_iterator
    request = next(request_iterator)
TypeError: 'list' object is not an iterator
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py in next(self)
     78         try:
---> 79             return six.next(self._wrapped)
     80         except grpc.RpcError as exc:

4 frames
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>

The above exception was the direct cause of the following exception:

Unknown                                   Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

Unknown: None Exception iterating requests!
```

**Comment by tseaver** [comment] 2019-07-02 17:24
The docs for the `requests` argument say:

> requests (iterator[dict|google.cloud.pubsub_v1.proto.pubsub_pb2.StreamingPullRequest]): The input objects. If a dict is provided, it must be of the same form as the protobuf message :class:`~google.cloud.pubsub_v1.types.StreamingPullRequest`

Dictionaries must match the attributes of that [protobuf message](https://googleapis.github.io/google-cloud-python/latest/pubsub/types.html#google.cloud.pubsub_v1.types.StreamingPullRequest).  However, the issue you are reporting here is that passing a `list` instance is raising the exception, before any of the dictionaries is used to construct a message.

If you construct the same list of dicts, but pass through the `iter` of it, does that work?  E.g.:

```python
from google.cloud import pubsub_v1

client = pubsub_v1.SubscriberClient()
subscription = client.subscription_path('[PROJECT]', '[SUBSCRIPTION]')
stream_ack_deadline_seconds = 0
request = {'subscription': subscription, 'stream_ack_deadline_seconds': stream_ack_deadline_seconds}
requests = [request]

for element in client.streaming_pull(iter(requests)):
    do_something_with(element)
```

**Comment by tseaver** [comment] 2019-07-02 17:25
The `StreamingPull` stub is defined as `stream_stream`, which is why the requests must be an iterator.  I don't really see the usecase for that, myself.  @lukesneeringer, @theacodes do either of you recall a rationale?

**Comment by ostrokach** [comment] 2019-07-02 17:36
I tried doing `iter(requests)` as well and would get a different error:

```python-traceback
Exception serializing message!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/grpc/_common.py", line 87, in _transform
    return transformer(message)
TypeError: descriptor 'SerializeToString' requires a 'google.protobuf.pyext._message.CMessage' object but received a 'dict'
---------------------------------------------------------------------------
_Rendezvous                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/api_core/grpc_helpers.py in next(self)
     78         try:
---> 79             return six.next(self._wrapped)
     80         except grpc.RpcError as exc:

4 frames
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception serializing request!"
	debug_error_string = "None"
>

The above exception was the direct cause of the following exception:

InternalServerError                       Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InternalServerError: 500 Exception serializing request!
```

**Comment by theacodes** [comment] 2019-07-02 17:43
`streaming_pull` is a low-level method and you're really not intended to use it directly. The pubsub streaming pull protocol is pretty complicated and `subscribe` does [a *lot* of machinery](https://github.com/googleapis/google-cloud-python/tree/master/pubsub/google/cloud/pubsub_v1/subscriber/_protocol) to properly open and maintain the stream.

This is as intended. Instead, use `subscribe` [as documented here](https://cloud.google.com/pubsub/docs/pull) or the non-streaming `pull` [as documented here](https://cloud.google.com/pubsub/docs/pull#synchronous_pull).

Closing for now, but feel free to continue the discussion.

**Closed by theacodes** 2019-07-02 17:43 UTC
Labels: api: pubsub, type: docs

**Comment by ostrokach** [comment] 2019-07-02 19:01
In any case, I think the documentation for `SubscriberClient.streaming_pull` should still be updated, either including a code snippet that actually works, or removing the code snippet or the method altogether from the documentation.

Otherwise, other people may end up wasting their time trying to figure out why the provided code does not work, trying different Python versions, etc.
