### ISSUE TITLE
Incorrect links on PyPi

### ISSUE THREAD

**Issue by steffnay** [googleapis/google-cloud-python#10795] opened 2022-12-08 21:17 UTC
The "Homepage" links on the PyPi pages for the latest release of libraries from this repository no longer point to this repo. The URLs have reverted back to the former individual API repository locations.

Example:
https://pypi.org/project/google-cloud-discoveryengine/0.2.1

It looks like the change in [url values](https://github.com/googleapis/google-cloud-python/blob/2e614c383621ae731280a1da30646d95b739e3e4/packages/google-cloud-discoveryengine/setup.py#L45) in setup.py was introduced by the gapic generator update in #10782

**Comment by parthea** [comment] 2023-08-01 15:03
The url value is currently populated via post processing [here](https://github.com/googleapis/synthtool/blob/c08afeed6d21ad6eaeab686459bc262453820aad/synthtool/languages/python_mono_repo.py#L92).

The issue with the broken link has been fixed but the link is still incorrect.

See https://pypi.org/project/google-cloud-netapp/ which was recently launched. The homepage points to https://github.com/googleapis/google-cloud-python instead of https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-netapp

**Comment by parthea** [comment] 2023-11-08 15:39
Closing as a duplicate of https://github.com/googleapis/gapic-generator-python/issues/1543

**Closed by parthea** 2023-11-08 15:39 UTC
Labels: type: bug, priority: p2
