### ISSUE TITLE
"invalid resource name" error with + in pubsub topic name

### ISSUE THREAD

**Issue by aaronhong** [googleapis/google-cloud-python#10386] opened 2020-03-10 09:04 UTC
Trying to create a pubsub topic with a plus symbol `+`, although [a valid name](https://cloud.google.com/pubsub/docs/admin#resource_names), does not work. I could not find a place to file issues against the gcloud SDK, so I thought I'd try here because the CLI just uses the googleapis anyways (although I'm not sure which language).

`my-deployment.yaml`
```yaml
resources:
  # topics
- name: my-topic
  type: pubsub.v1.topic
  properties:
    topic: my-topic+suffix
```

```shell
$ gcloud deployment-manager deployments create my-deployment --config my-deployment.yaml
```

Error message:
```
- code: RESOURCE_ERROR
  location: /deployments/my-deployment/resources/my-topic
  message: '{"ResourceType":"pubsub.v1.topic","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid
    resource name given (name=projects/{project name}/topics/my-topic suffix).
    Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.","status":"INVALID_ARGUMENT","details":[],"statusMessage":"Bad
    Request","requestPath":"https://pubsub.googleapis.com/v1/projects/{project name}/topics/my-topic+suffix","httpMethod":"PUT"}}'
```

It seems like the google apis is interpreting the `+` as a space. Although the [documentation for valid pubsub resource names](https://cloud.google.com/pubsub/docs/admin#resource_names) seem to indicate it should work:
> The special characters in the above list can be used in resource names without URL-encoding... This is particularly important for REST calls.

Seems like I found an issue and pull request here: https://github.com/googleapis/google-http-java-client/issues/398

```shell
$ gcloud --version
Google Cloud SDK 283.0.0
beta 2019.05.17
bq 2.0.54
core 2020.02.28
gsutil 4.48
pubsub-emulator 2019.09.27
```

**Comment by busunkim96** [comment] 2020-03-10 17:13
@aaronhong Thanks for filing an issue! 

@hongalex Does this seem like a Pub/Sub issue or a gcloud issue?

**Comment by hongalex** [comment] 2020-03-10 19:25
So I tried `gcloud pubsub create topic test+Topic` and that seems to work. Similarly, the [REST API](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics/create) seems to work fine as well.

This means the issue is probably related to the deployment manager. @busunkim96 Do you know where we can route this to?

**Comment by busunkim96** [comment] 2020-03-10 19:38
Ah I see. Thanks for investigating!

@aaronhong would you mind filing an issue on [Deployment Manager's public issue tracker](https://issuetracker.google.com/issues/new?component=187078&template=0)? I can also open one  on your behalf if you would prefer that.

**Comment by aaronhong** [comment] 2020-03-11 06:34
Thanks, created an issue there: https://issuetracker.google.com/u/1/issues/151168541

I tried it in the API explorer and it works, but what baffles me is it seems like the Deployment Manager is using the REST API also, no?

From what I see, it's doing a `PUT` with the same and correct request path:
```
"requestPath":"https://pubsub.googleapis.com/v1/projects/{project name}/topics/my-topic+suffix"
```

And the error message (that shows the incorrect resource name) is also from said API?
> Invalid resource name given (name=projects/{project name}/topics/my-topic suffix). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.

**Comment by busunkim96** [comment] 2020-03-11 16:12
Hi @aaronhong, I unfortunately don't know the internals of Deployment Manager. You'll get the best answers by communicating with the person on the issuetracker.google.com issue.

Closing this issue as it is tracked in https://issuetracker.google.com/u/1/issues/151168541.

**Closed by busunkim96** 2020-03-11 16:12 UTC
Labels: external, triage me
