### ISSUE TITLE
Batch jobs method support for instances client level  in Python Google cloud compute engine client library

### ISSUE THREAD

**Issue by googlesupporttech** [googleapis/google-cloud-python#11860] opened 2023-10-02 19:47 UTC
Thanks for stopping by to let us know something could be better!

I am from GCP Google support and I am creating this FR as the Customers are requesting the batch jobs support for python Cloud client library based on the following links:

- https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.instances.InstancesClient
- https://github.com/googleapis/python-compute/blob/main/google/cloud/compute_v1/services/instances/client.py

**Comment by parthea** [comment] 2023-11-08 02:34
Closing as a duplicate of https://github.com/googleapis/gapic-generator-python/issues/1519

**Closed by parthea** 2023-11-08 02:34 UTC
Labels: type: feature request, api: compute
