### ISSUE TITLE
Create separate presubmits for docs builds: `docs_preview` and `docs_release`

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#12004] opened 2023-11-08 15:08 UTC
The purpose is to allow PRs to be merged with docs warnings, while allowing maintainers to have visibility of the warnings so they can be addressed in the long term.

`docs_preview` will run the docs build with warnings treated as errors.
`docs_release` will run the docs build without warnings treated as errors.

**Comment by vchudnov-g** [comment] 2024-05-17 19:36
Fixed in #12708. Verified in that PR for non-merge PRs. 

I'll close this issue for now, but we will pay attention to the next merge PR to ensure the docs checks indeed ran. If they didn't, we will re-open this issue and re-address.

**Comment by vchudnov-g** [comment] 2024-05-22 22:42
The release PR #12720 is not running the `docs` and `docfx` checks as intended, so there's something wrong with the triggering. Re-opening.

**Comment by vchudnov-g** [comment] 2024-05-23 17:56
Fixed: now the docs checks are running and blocking on merge PRs, as intended. Closing again.

**Closed by vchudnov-g** 2024-05-23 17:56 UTC
Labels: type: process
