### ISSUE TITLE
PubSub: Subscriber hangs when passed credentials kwarg with invalid type

### ISSUE THREAD

**Issue by jceresini** [googleapis/google-cloud-python#7419] opened 2019-02-22 01:11 UTC
When using the `google-auth` library and passing `credentials=google.auth.default()` to `pubsub_v1.SubscriberClient` the subscriber hangs. No errors are shown, and the callback is never triggered. I made a simplified example below that demonstrates the issue. In the example code, if the subscription doesn't exist, or if the user/serviceAccount doesn't have permissions to subscribe to the topic, the code just hangs at `future.result()`. If I remove the `credentials` kwarg when I create the subscriber, the appropriate exceptions are raised and the code exits as expected. If there are no issues preventing the user/serviceAccount from subscribing to the topic, and there are messages waiting to be acked, it also hangs and seemingly does nothing. Again, if I remove the credentials kwarg, it starts receiving messages, and calling the callback.

I realize this is kind of a silly example, since it uses the application default credentials when no credentials are explicitly passed anyway. I wrote my code that way to make it easy to share with others with a comment that you could plug-in credentials using whatever method you preferred.

```
from google.cloud import pubsub_v1
import google.auth


def callback(message):
    print(message)


if __name__ == "__main__":

    app_creds = google.auth.default()

    subscriber = pubsub_v1.SubscriberClient(credentials=app_creds)
    subscription_path = subscriber.subscription_path(
        'myproject', 'mysubscription')

    future = subscriber.subscribe(
        subscription_path,
        callback=callback
    )

    print("Listening for pubsub messages on {}...".format(subscription_path))
    future.result()
```

**Comment by jceresini** [comment] 2019-02-22 01:27
I just realized that `google.auth.default()` returns a tuple, so I was using it incorrectly. I still think an exception should have been raised that auth failed, or that the credentials were not the correct type, etc.

**Comment by jceresini** [comment] 2019-02-22 02:08
It looks like the Client defined in core detects invalid credentials and handles them appropriately: https://github.com/googleapis/google-cloud-python/blob/master/core/google/cloud/client.py#L125

The clients in some other libraries seem to inherit from that class, and call the parent classes constructor, which would raise an exception on bad credentials:

https://github.com/googleapis/google-cloud-python/blob/master/logging/google/cloud/logging/client.py#L59
https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L95

The pubsub SubscriberClient inherets from Object, and doesn't implement its own credentials type validation.

**Comment by sduskis** [comment] 2019-06-11 13:12
This is a duplicate of #7199

**Closed by sduskis** 2019-06-11 13:12 UTC
Labels: api: pubsub, type: question
