### ISSUE TITLE
Logging: support sending 'jsonPayload' via the python logger

### ISSUE THREAD

**Issue by joseret** [googleapis/google-cloud-python#6657] opened 2018-11-27 23:36 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Clear and consistent mechanism to populate stackdriver log jsonPayload using the python logger.

 **Describe the solution you'd like**
This has been described that if you pass a JSON string (startsWith '{' and you can parse valid json, then the jsonPayload will contain this json (override time and severity at least for consistency)
It should be the same in all environments. GCE, GKE, GCF, Python Client, GAE, and future GCP using the python runtimes.

 **Describe alternatives you've considered**
No other solution seems to be a better option

 **Additional context**
In the interest of keeping the consistency of native code and less coupling to the underlying logging mechanism.

**Comment by tseaver** [comment] 2018-11-28 18:19
Related to #6488.  The essential problem is that the Python stdlib logging mechansim doesn't contemplate this idea, which means a lot of ugliness to try to work around that.

**Comment by tseaver** [comment] 2018-11-28 18:20
Duplicate of #6354.

**Closed** 2018-11-28 18:20 UTC
Labels: api: logging, status: duplicate, type: question
