### ISSUE TITLE
pubsub system test: "failed with exit code -11"

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#5479] opened 2018-06-12 21:10 UTC
Pubsub system tests run successfully, but [die occasionally](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6873) with a segfault(?) on exit:

```
nox > Running session system(py='2.7')
nox > /usr/local/bin/python3.6 -m virtualenv /var/code/gcp/.nox/sys-2-7 -p python2.7
nox > chdir /var/code/gcp/pubsub
nox > pip install --upgrade --pre grpcio
nox > pip install --upgrade mock pytest ../api_core ../core
nox > pip install --upgrade ../test_utils/
nox > pip install --upgrade .
nox > py.test --quiet tests/system.py
...                                                                      [100%]
3 passed in 30.45 seconds
nox > Command py.test --quiet tests/system.py failed with exit code -11
nox > Session system(py='2.7') failed.
```

**Comment by tseaver** [comment] 2018-06-12 21:19
See also [another CI failures](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/6828) with the same symptom.

**Comment by theacodes** [comment] 2018-06-13 17:32
hrm, a segfault would point to grpc as the likely culprit. @mehrdada are there any know segfaulting bugs in gRPC on Python 2.7?

**Comment by tseaver** [comment] 2018-06-13 17:38
Given that the tests all pass, my suspicion is a race condition during teardown of socket resources during process exit.

**Comment by mehrdada** [comment] 2018-06-13 18:38
@theacodes Nothing off the top of my head. Does this happen only on `--pre` build? We uploaded a new one just a couple days back.

**Comment by theacodes** [comment] 2018-06-13 18:48
Yeah our system tests use pre, but idk if it doesn't happen otherwise.

**Comment by mehrdada** [comment] 2018-06-13 19:00
@theacodes I'd be really interested to know if it is a newly introduced regression in v1.13.0-pre1 before we mark the RC1 as final.

Where can we see a stack trace denoting where the exception occurs? I couldn't find it looking at the linked page.

**Comment by theacodes** [comment] 2018-06-13 19:08
> Where can we see a stack trace denoting where the exception occurs?

SIGSEGV at process exit doesn't tend to produce a stacktrace iirc.

Since we run our system tests in quiet mode, you'll need to run them yourself and specify verbosity and disable output capture, e.g.:

```
nox -s "system(py='2.7')" -- -vvv -s
```

**Comment by mehrdada** [comment] 2018-06-15 15:36
https://github.com/grpc/grpc/pull/15781 might fix this

**Comment by tseaver** [comment] 2018-06-15 16:37
@mehrdada That looks like a good candidate.

**Comment by mehrdada** [comment] 2018-06-15 18:57
Irrespective of this particular bug, it'd be amazing if your CI tested on gRPC under both `--pre` and latest non-pre to confirm what users actually experience in the wild keeps working.

**Comment by mehrdada** [comment] 2018-06-16 01:29
1.13.0rc2 is uploaded. Please test. I hope it fixes the issue.

**Comment by theacodes** [comment] 2018-06-18 17:28
I'm going to preemptively close this, but if it shows up again please re-open, @tseaver.

**Comment by mehrdada** [comment] 2018-06-18 17:29
Glad we have not been seeing it for the past few days.

**Comment by tseaver** [comment] 2018-07-25 18:12
Surfaced again [today](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7388).

**Comment by mehrdada** [comment] 2018-07-25 18:14
We have uploaded 1.14.0rc1 today. Is your system picking that up?

**Comment by mehrdada** [comment] 2018-07-25 18:19
Have you tried calling `Channel.close` when you are done with a Channel?

**Comment by tseaver** [comment] 2018-07-25 18:40
@mehrdada 

> We have uploaded 1.14.0rc1 today. Is your system picking that up?

Yes, I think so.  We install it via `pip install --upgrade --pre grpcio`

> Have you tried calling Channel.close when you are done with a Channel?

Both system tests which set up BIDI streams do end up calling `Channel.close`, via:
-  `future.cancel()` aka `subscriber.futures.StreamingPullFuture.cancel`
- `self._manager.close()` aka `subscriber._protocol.streaming_pull_manager.StreamingPullManager.close`
- `self._consumer.stop()` aka `subscriber._protocol.bidi.BackgroundConsumer.stop`
- `self._bidi_rpc.close()` aka `grpc.Channel.close`

**Comment by tseaver** [comment] 2018-08-28 17:11
[Another failure today](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7815)

**Comment by tseaver** [comment] 2018-09-11 19:46
[Another failure today](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/7984)

**Comment by srini100** [comment] 2018-09-11 19:55
This fix https://github.com/grpc/grpc/pull/16296 might help? It will be available in gRPC v1.15.0 coming out shortly. See the related issue https://github.com/grpc/grpc/issues/16290. There are still some race conditions that need to be debugged.

**Comment by tseaver** [comment] 2018-09-13 18:57
@srini100 As of today, our test configuration picks up `grpcio-1.15.0`.  Fingers crossed.

**Comment by srini100** [comment] 2018-12-08 00:46
@tseaver, does it look like this issue is resolved? It's been a while since you reported a failure.

**Comment by tseaver** [comment] 2018-12-10 22:09
@srini100 Thanks very much for the fix, and the follow-up.

**Closed** 2018-12-10 22:09 UTC
Labels: api: pubsub, flaky, testing, type: process
