### ISSUE TITLE
(A single, complete) Cloud Client Library for IAM

### ISSUE THREAD

**Issue by rrrix** [googleapis/google-cloud-python#10643] opened 2022-05-03 21:27 UTC
# Right Place for Missing APIs?

I'm not sure if this is the right place to open an issue for this. If this is **_not_** the right place, can someone please point me to where I should post this request??

----

Hi Googlers,

I'm requesting the [Identity and Access Management IAM API](https://cloud.google.com/iam/docs/reference/rest) (e.g. `https://iam.googleapis.com`) be added as a supported Python Cloud Client Library.

I believe it is both reasonable _and expected_ for the existing [Identity and Access Management (python-iam)](https://github.com/googleapis/python-iam) package fully support **_all_** IAM APIs. That was my first place to look for working with IAM Roles, Permissions, and Service Accounts. I thought my brain was having a short circuit and that I made a mistake when I saw what is really _only_ the [Service Account Credentials API](https://cloud.google.com/iam/docs/reference/credentials/rest) (e.g. `https://iamcredentials.googleapis.com`).

As far as code generation goes, [googleapis/googleapis](https://github.com/googleapis/googleapis) has **full and complete definitions for all IAM APIs**:

* [iam/admin/v1/iam.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/admin/v1/iam.proto)
  * Endpoint: `iam.googleapis.com`
  * All Standard Methods (List, Get, Create, Update, Delete) for All `admin/v1` Resources (Service Accounts, Service Account Keys, Roles, Permissions)
  * All Custom Methods (TestIamPermissions, QueryGrantableRoles, QueryTestablePermissions, QueryAuditableServices, LintPolicy)
* [iam/credentials/v1/iamcredentials.proto](http://github.com/googleapis/googleapis/blob/master/google/iam/credentials/v1/iamcredentials.proto)
  * This is currently the only API that is already in the [`python-iam`](https://github.com/googleapis/python-iam) package.
  * Endpoint: `iamcredentials.googleapis.com`
  * All Methods: GenerateAccessToken, GenerateIdToken, SignBlob, SignJwt
* [iam/v1/iam_policy.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/v1/iam_policy.proto)
  * Endpoint: `iam-meta-api.googleapis.com`
  * All Standard Methods (SetIamPolicy, GetIamPolicy, TestIamPermissions)
  * Requires [iam/v1/policy.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/v1/policy.proto)
* [iam/v1beta/workload_identity_pool.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/v1/workload_identity_pool.proto)
  * Endpoint: `iam.googleapis.com`
  * All Standard Methods (List, Get, Create, Update, Delete) for `v1beta` Workload Identity Pools
* [iam/v2beta/policy.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/v2beta/policy.proto) and [iam/v2beta/deny.proto](https://github.com/googleapis/googleapis/blob/master/google/iam/v2beta/deny.proto)
  * Endpoint: `iam.googleapis.com`
  * The new and very awesome `v2beta` IAM Policies API
  * _CRUDL_ for IAM Policies
  * Includes the new _Deny_ policies API

I was a little surprised to find IAM does not have complete support in the Python Cloud Client Libraries. Seems like an oversight? I mean... You can't really _do_ Google Cloud without IAM... :) 

Also, it might be worth looking at how the current "IAM" libraries are named / described, since it's very confusing unless you take a few hours to read through all of the code and documentation for each of the packages (as I did). 

To be honest, it was a poor developer/user experience [constantly being](https://github.com/googleapis/google-api-python-client#other-google-api-libraries) [directed](https://cloud.google.com/apis/docs/client-libraries-explained) [to use](https://cloud.google.com/iam/docs/reference/libraries#:~:text=Many%20Google%20Cloud,libraries%20explained.) [Client Libraries](https://cloud.google.com/iam/docs/reference/rest#:~:text=To%20call%20this%20service%2C%20we%20recommend%20that%20you%20use%20the%20Google%2Dprovided%20client%20libraries.%20If%20your%20application%20needs%20to%20use%20your%20own%20libraries%20to%20call%20this%20service%2C%20use%20the%20following%20information%20when%20you%20make%20the%20API%20requests.) that don't exist.

Currently, Python Cloud Client Libraries lists _two different versions_ of "Identity and Access Management" packages, one "IAM Logging Protos" package and one "IAM Policy Troubleshooter API" package listed in the [README](https://github.com/googleapis/google-cloud-python/blob/main/README.rst):

* [Identity and Access Management (python-iam)](https://github.com/googleapis/python-iam)
* [Identity and Access Management (python-grpc-google-iam-v1)](https://github.com/googleapis/python-grpc-google-iam-v1)
* [IAM Logging Protos (python-iam-logging)](https://github.com/googleapis/python-iam-logging)
* [IAM Policy Troubleshooter API (python-policy-troubleshooter)](https://github.com/googleapis/python-policy-troubleshooter)

I'm not sure why the first two are _both_ called "Identity and Access Management" when neither of them are full IAM APIs. The "IAM Logging Protos" is the only library appropriately named for its specific limited subset of IAM functionality.

The [python-grpc-google-iam-v1](https://github.com/googleapis/python-grpc-google-iam-v1) package is even more mysterious, as it a [single subdirectory (iam/v1/)](https://github.com/googleapis/python-grpc-google-iam-v1/tree/main/google/iam/v1) which appears to be generated or copied from the [googleapis/google/iam](https://github.com/googleapis/googleapis/tree/master/google/iam/v1) interface definitions. 🤔 

I hope we can get a nice idiomatic & Pythonic Google Cloud IAM SDK at some point. Thanks in advance!

**Comment by parthea** [comment] 2022-05-05 01:38
Closing as duplicate of https://github.com/googleapis/python-iam/issues/187

**Closed by parthea** 2022-05-05 01:38 UTC
Labels: type: bug, priority: p2
