### ISSUE TITLE
'Credentials' object has no attribute 'universe_domain' in package google-analytics-data: 

### ISSUE THREAD

**Issue by chewei888** [googleapis/google-cloud-python#12254] opened 2024-02-02 00:38 UTC
I am experiencing an error with a Python script that has been working well since 2023. The script's main function is to extract sessions from Google Analytics 4 via the package google-analytics-data. However, after 7:30 AM PST on February 1, 2024, I received an error message stating that the 'Credentials' object has no attribute 'universe_domain'. 'universe_domain' is one of the attributes in the API key JSON file.

My script followed the guidance provided by Google in this link https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries (I copied the example Python codes below), and I also referred to this article https://automation-help.com/google-analytics-data-api-ga4-with-python-extensive-guide/. I can confirm that my API key is not expired and is working correctly. My service account is also enabled and running, with the proper permission in the GA property access management.

I believe the issue is with the Python package google-analytics-data itself, and I am wondering if anyone else has encountered a similar issue or has found a root cause or solution. Could someone please provide me with some information?

```
​from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
)


def sample_run_report(property_id="YOUR-GA4-PROPERTY-ID"):
    """Runs a simple report on a Google Analytics 4 property."""
    # TODO(developer): Uncomment this variable and replace with your
    #  Google Analytics 4 property ID before running the sample.
    # property_id = "YOUR-GA4-PROPERTY-ID"

    # Using a default constructor instructs the client to use the credentials
    # specified in GOOGLE_APPLICATION_CREDENTIALS environment variable.
    client = BetaAnalyticsDataClient()

    request = RunReportRequest(
        property=f"properties/{property_id}",
        dimensions=[Dimension(name="city")],
        metrics=[Metric(name="activeUsers")],
        date_ranges=[DateRange(start_date="2020-03-31", end_date="today")],
    )
    response = client.run_report(request)

    print("Report result:")
    for row in response.rows:
        print(row.dimension_values[0].value, row.metric_values[0].value)
```

**Comment by brianliefinaccel** [comment] 2024-02-02 00:48
Most probably because of release https://github.com/googleapis/google-cloud-python/pull/12243

**Comment by ohmayr** [comment] 2024-02-02 01:05
We're looking into this issue. 

Seems like version of `googl-auth` that you're using does not expose `universe_domain` as a property of credentials (This is expected).

@brianliefinaccel for now, can you please try upgrading the google-auth version to [v2.23.0](https://github.com/googleapis/google-auth-library-python/releases/tag/v2.23.0). Let us know if that resolves the issue for you!

**Comment by brianliefinaccel** [comment] 2024-02-02 01:26
@ohmayr we ended up locking our package versions to version before yesterday's release because urgency, which works to fix the issue. For `google-auth` I'll see if we can deploy the upgrade for the other half of our code and report back here.

**Comment by brianliefinaccel** [comment] 2024-02-02 01:38
I can confirm upgrading to `google-auth` version 2.23.0 works @ohmayr 

previously our `google-auth` version is stuck on v1.35 because we added `google-cloud-bigquery==2.20.0` into our dependency, but installing latest version of `google-cloud-secret-manager` does not upgrade the `google-auth` package.

I think it is already addressed in https://github.com/googleapis/gapic-generator-python/issues/1922

**Comment by chewei888** [comment] 2024-02-02 01:49
@ohmayr and @brianliefinaccel,
 
Thank you for providing the solution. After upgrading `google-auth`, the issue related to `universe_domain` has been resolved.

`pip install --upgrade google-auth`
`dbutils.library.restartPython()`

**Comment by Yourius** [comment] 2024-02-02 12:17
> I am experiencing an error with a Python script that has been working well since 2023. The script's main function is to extract sessions from Google Analytics 4 via the package google-analytics-data. However, after 7:30 AM PST on February 1, 2024, I received an error message stating that the 'Credentials' object has no attribute 'universe_domain'. 'universe_domain' is one of the attributes in the API key JSON file.
> 
> My script followed the guidance provided by Google in this link https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries (I copied the example Python codes below), and I also referred to this article https://automation-help.com/google-analytics-data-api-ga4-with-python-extensive-guide/. I can confirm that my API key is not expired and is working correctly. My service account is also enabled and running, with the proper permission in the GA property access management.
> 
> I believe the issue is with the Python package google-analytics-data itself, and I am wondering if anyone else has encountered a similar issue or has found a root cause or solution. Could someone please provide me with some information?
> 
> ```
> ​from google.analytics.data_v1beta import BetaAnalyticsDataClient
> from google.analytics.data_v1beta.types import (
>     DateRange,
>     Dimension,
>     Metric,
>     RunReportRequest,
> )
> 
> 
> def sample_run_report(property_id="YOUR-GA4-PROPERTY-ID"):
>     """Runs a simple report on a Google Analytics 4 property."""
>     # TODO(developer): Uncomment this variable and replace with your
>     #  Google Analytics 4 property ID before running the sample.
>     # property_id = "YOUR-GA4-PROPERTY-ID"
> 
>     # Using a default constructor instructs the client to use the credentials
>     # specified in GOOGLE_APPLICATION_CREDENTIALS environment variable.
>     client = BetaAnalyticsDataClient()
> 
>     request = RunReportRequest(
>         property=f"properties/{property_id}",
>         dimensions=[Dimension(name="city")],
>         metrics=[Metric(name="activeUsers")],
>         date_ranges=[DateRange(start_date="2020-03-31", end_date="today")],
>     )
>     response = client.run_report(request)
> 
>     print("Report result:")
>     for row in response.rows:
>         print(row.dimension_values[0].value, row.metric_values[0].value)
> ```

sdfdg

**Comment by Yourius** [comment] 2024-02-02 12:22
I've faced the same issue. But the project was in Colab. I fixed it with

`!pip install google-analytics-data==0.18.3`

New version was released on February, 1, 2024 (google-analytics-data 0.18.4) and that one has errors yet.

**Comment by honnix** [comment] 2024-02-02 13:33
Looks like this is also a problem in google-cloud-kms lib, where google-auth is not claimed to be a dependency https://github.com/googleapis/google-cloud-python/blob/6dd0a9a4f0ec8de49630b1caa1a57b45df33f376/packages/google-cloud-kms/setup.py#L42C6-L45, while it should have been because it is directly used https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-kms/google/cloud/kms_v1/services/key_management_service/client.py#L37-L40.

google-cloud-kms relies on google-api-core to introducing google-auth as a transitive dependency but https://github.com/googleapis/python-api-core/blob/5922f2b8f382ee1fd9b69fafb2eed39db93b60fb/setup.py#L34 is not good enough for google-cloud-kms because it may install a previous version of google-auth.

**Comment by adamcathersides** [comment] 2024-02-02 16:37
I have been also seeing the same issue when trying to run the resource manager [sample code](https://github.com/googleapis/google-cloud-python/blob/main/packages/google-cloud-resource-manager/samples/generated_samples/cloudresourcemanager_v3_generated_projects_get_iam_policy_sync.py) to get the iam policy.

I upgraded the `google-auth` to latest (`2.27.0`) and now I get 
```
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.
```

**Comment by jose-neta** [comment] 2024-02-02 17:51
> We're looking into this issue.
> 
> Seems like version of `google-auth` that you're using does not expose `universe_domain` as a property of credentials (This is expected).
> 
> @brianliefinaccel for now, can you please try upgrading the google-auth version to [v2.23.0](https://github.com/googleapis/google-auth-library-python/releases/tag/v2.23.0). Let us know if that resolves the issue for you!

On GCP Colab Enterprise here, and `!pip install --upgrade google-auth` solves it, thank you

**Comment by adamcathersides** [comment] 2024-02-04 19:53
FYI - I have got this example working now. It appears I was defining one of the resources incorrectly!
So upgrading `google-auth` also worked for me

**Comment by Bharathi-anjuri** [comment] 2024-02-05 05:57
I'm using google-cloud-secret-manager==2.16.4 google-auth==2.23.0/2.27.0, however im still facing below error
SecretManagerServiceClient._compare_universes(
  File "/opt/conda/default/lib/python3.8/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 525, in _compare_universes
    credentials_universe = credentials.universe_domain
AttributeError: 'Credentials' object has no attribute 'universe_domain'

**Closed** 2024-02-07 17:17 UTC
Labels: type: bug, priority: p1

**Comment by chaserracerr** [comment] 2024-02-08 16:24
@parthea following up on this - can you confirm this was a Google related issue that required support from Google, or was this purely within our universe that required changes. Want to ensure we got the right amount of support from Google (if needed) - thanks

**Comment by parthea** [comment] 2024-02-08 17:05
Hi @chaserracerr,

Regrettably, I don't have access to the discussions that you shared in Workplace. Only public information about the code or issues in Github should be shared in this thread. Here is some context about the issue in this thread:

The issue reported in this bug only occurs with older versions of `google-auth` (v2.22.0 or older from July 2023). The root cause is that the minimum version of `google-auth` was not stated for python client libraries, which is why this issue slipped through our testing. A [workaround was provided](https://github.com/googleapis/google-cloud-python/issues/12254#issuecomment-1922600787) about 30 minutes after the issue opened suggesting to use a newer version of `google-auth`, which is version [v2.23.0](https://github.com/googleapis/google-auth-library-python/releases/tag/v2.23.0) or newer. I can confirm that the testing gap has been addressed and a fix was released yesterday via https://github.com/googleapis/google-cloud-python/pull/12258.

**Comment by parthea** [comment] 2024-02-08 17:42
Correct. We're working on building automation to avoid a repeat of the issue where a dependency is used but the minimum version for the dependency is not stated: https://github.com/googleapis/gapic-generator-python/issues/1924

**Comment by chaserracerr** [comment] 2024-02-08 22:57
I've raised the question with Google to ensure the documentation is update [here](https://shopify.slack.com/archives/C73QZF6D8/p1707428901798089) (in #google-external)

**Comment by jhkim1067** [comment] 2024-11-27 02:48
I'm using google-auth==2.36.0, but I'm still having issues. It's critical.

**Comment by parthea** [comment] 2024-11-27 15:32
@jhkim1067  Please include the stack trace if it's available.

**Comment by botchagalupe** [comment] 2024-11-27 16:53
This user is impersonating my email.

**Comment by botchagalupe** [comment] 2024-11-27 17:00
@jhkim1067  is impersoning my email address. Please fix this ASAP.

**Comment by jhkim1067** [comment] 2024-12-13 01:20
I don't know what you're talking about @botchagalupe , I'm an LG employee and I have that email address.

**Comment by jhkim1067** [comment] 2024-12-13 01:22
I have resolved the issue @parthea  by downgrading immediately. I will share the stacktrace as soon as we have it, thank you.
