### ISSUE TITLE
Bigtable, Container: current releases pin incompatible 'grpc-google-iam-v1' with current releases.

### ISSUE THREAD

**Issue by zunger-humu** [googleapis/google-cloud-python#8807] opened 2019-07-29 20:56 UTC
Today's google-cloud-pubsub 0.44 release is broken, as it appears to depend on an as-yet-unreleased version of google.iam.v1. If you attempt to use it with the current release version of that library, the diagnostic failure is:

```
    from google.cloud import pubsub
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/__init__.py", line 18, in <module>
    from google.cloud.pubsub_v1 import publisher
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1.publisher.client import Client
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 29, in <module>
    from google.cloud.pubsub_v1.gapic import publisher_client
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 39, in <module>
    from google.cloud.pubsub_v1.gapic.transports import publisher_grpc_transport
  File "/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py", line 21, in <module>
    from google.iam.v1 import iam_policy_pb2_grpc as iam_policy_pb2_grpc
ImportError: cannot import name 'iam_policy_pb2_grpc' from 'google.iam.v1' (/Users/zunger/src/code/venv/lib/python3.7/site-packages/google/iam/v1/__init__.py)
```

Version 0.44 should probably be unpublished until a compatible IAM library is released.

**Comment by tseaver** [comment] 2019-07-29 21:16
@zunger-humu the dependencies for `google-cloud-pubsub 0.44 look correct to me: https://github.com/googleapis/google-cloud-python/blob/be9e45797039fa4e9b1249e48199f8909150f945/pubsub/setup.py#L31-L35

and I cannot reproduce in a fresh virtual environment:

```bash
$ python3.7 -m venv /tmp/gcp/8807
$ /tmp/gcp/8807/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.2.1 setuptools-41.0.1 wheel-0.33.4
$ /tmp/gcp/8807/bin/pip install google-cloud-pubsub==0.44.0
...
Successfully installed cachetools-3.1.1 certifi-2019.6.16 chardet-3.0.4 google-api-core-1.14.0 google-auth-1.6.3 google-cloud-pubsub-0.44.0 googleapis-common-protos-1.6.0 grpc-google-iam-v1-0.12.3 grpcio-1.22.0 idna-2.8 protobuf-3.9.0 pyasn1-0.4.5 pyasn1-modules-0.2.5 pytz-2019.1 requests-2.22.0 rsa-4.0 six-1.12.0 urllib3-1.25.3
$ /tmp/gcp/8807/bin/pip list
Package                  Version  
------------------------ ---------
cachetools               3.1.1    
certifi                  2019.6.16
chardet                  3.0.4    
google-api-core          1.14.0   
google-auth              1.6.3    
google-cloud-pubsub      0.44.0   
googleapis-common-protos 1.6.0    
grpc-google-iam-v1       0.12.3   
grpcio                   1.22.0   
idna                     2.8      
pip                      19.2.1   
protobuf                 3.9.0    
pyasn1                   0.4.5    
pyasn1-modules           0.2.5    
pytz                     2019.1   
requests                 2.22.0   
rsa                      4.0      
setuptools               41.0.1   
six                      1.12.0   
urllib3                  1.25.3   
wheel                    0.33.4 
$ /tmp/gcp/8807/bin/python -c "from google.cloud import pubsub; print(pubsub.__file__)"
/tmp/gcp/8807/lib/python3.7/site-packages/google/cloud/pubsub.py
```

Can you provide the output of `pip list` in your environment?

**Comment by barendlinders** [comment] 2019-07-30 13:01
We are running into the same issue when installing the following (on Dataproc):

```
pip install --upgrade pip
pip install --upgrade google-cloud-bigtable google-cloud-bigquery google-cloud-storage google-cloud-pubsub gcsfs
```






This results in the following `pip list`, where `grpc-google-iam-v1` is off with the version posted above by @tseaver. We have version `0.11.4` installed, while @tseaver has `0.12.3` installed. Will try to force it to `0.12.3` to see if this solves our problems.

Full `pip list`:

```gcsfs                    0.3.0     
google-api-core          1.14.0    
google-auth              1.6.3     
google-auth-oauthlib     0.4.0     
google-cloud-bigquery    1.17.0    
google-cloud-bigtable    0.33.0    
google-cloud-core        1.0.3     
google-cloud-pubsub      0.44.0    
google-cloud-storage     1.17.0    
google-resumable-media   0.3.2     
googleapis-common-protos 1.6.0     
grpc-google-iam-v1       0.11.4    
grpcio                   1.22.0    
idna                     2.6       
mkl-fft                  1.0.12    
mkl-random               1.0.2     
numpy                    1.16.4    
oauthlib                 3.0.2     
pandas                   0.24.2    
pip                      19.2.1    
protobuf                 3.9.0     
py4j                     0.10.7    
pyarrow                  0.11.1    
pyasn1                   0.4.5     
pyasn1-modules           0.2.5     
pycosat                  0.6.3     
pycparser                2.18      
pyOpenSSL                18.0.0    
PySocks                  1.6.8     
pyspark                  2.4.3
python-dateutil          2.8.0     
pytz                     2019.1    
requests                 2.18.4    
requests-oauthlib        1.2.0     
rsa                      4.0       
ruamel-yaml              0.15.37   
setuptools               41.0.1    
six                      1.12.0    
urllib3                  1.22      
wheel                    0.33.4

**Comment by barendlinders** [comment] 2019-07-30 13:42
After manually installing `pipdeptree` I get the following output:

```
Warning!!! Possibly conflicting dependencies found:
* google-cloud-pubsub==0.44.0
 - grpc-google-iam-v1 [required: >=0.12.3,<0.13dev, installed: 0.11.4]
------------------------------------------------------------------------
```
[pipdeptree.txt](https://github.com/googleapis/google-cloud-python/files/3447036/pipdeptree.txt)

Full pipdeptree attached as pipdeptree.txt

**Comment by thrykol** [comment] 2019-07-30 16:00
I believe it's a requirement conflict between `google-cloud-spanner` and `google-cloud-pubsub`.  In my environment `pipdeptree` reports 
```
grpc-google-iam-v1 [required: >=0.11.4,<0.12dev, installed: 0.11.4]
grpc-google-iam-v1 [required: >=0.12.3,<0.13dev, installed: 0.11.4]
```
for the two libraries respectively if I don't specify a version in my `requirements.txt`.

**Comment by zunger-humu** [comment] 2019-07-30 16:55
Aha! That would explain the issue. So, hmm -- any thoughts as to the best
way to fix it?

**Comment by thrykol** [comment] 2019-07-30 17:14
@zunger-humu My short term solution was to explicitly set the version of `google-cloud-pubsub` in my `requirements.txt`.

`google-cloud-pubsub==0.42.1`

**Comment by tseaver** [comment] 2019-07-30 17:15
@thrykol `google-cloud-spanner 1.10.0` has the "correct" dependencies for `grpc-google-iam-v1':

```python
name = "google-cloud-spanner"
description = "Cloud Spanner API client library"
version = "1.10.0"
# Should be one of:
# 'Development Status :: 3 - Alpha'
# 'Development Status :: 4 - Beta'
# 'Development Status :: 5 - Production/Stable'
release_status = "Development Status :: 5 - Production/Stable"
dependencies = [
    "google-api-core[grpc, grpcgcp] >= 1.14.0, < 2.0.0dev",
    "google-cloud-core >= 1.0.0, < 2.0dev",
    "grpc-google-iam-v1 >= 0.12.3, < 0.13dev",
]
```

However, in @barendlinders' example, `google-cloud-bigtable-0.33.0` is too old for that pin.  It still has:

```python
name = 'google-cloud-bigtable'
description = 'Google Cloud Bigtable API client library'
version = '0.33.0'
# Should be one of:
# 'Development Status :: 3 - Alpha'
# 'Development Status :: 4 - Beta'
# 'Development Status :: 5 - Production/Stable'
release_status = 'Development Status :: 4 - Beta'
dependencies = [
    'google-api-core[grpc] >= 1.6.0, < 2.0.0dev',
    "google-cloud-core >= 1.0.0, < 2.0dev",
    'grpc-google-iam-v1 >= 0.11.4, < 0.12dev',
]
```

I have just made PR #8827 to push out a new release of `google-cloud-bigtable` with updated pins.

**Comment by zunger-humu** [comment] 2019-07-30 17:18
Thank you!

**Comment by thrykol** [comment] 2019-07-30 17:34
@tseaver Interesting.  Was that version just released?  I was having issues this morning with deploying some functions in GCP due to this issue.  But now I'm seeing the update there (from `1.9.0`) as well as the correct iam version.

**Comment by tseaver** [comment] 2019-07-30 17:46
Both `bigtable` and `container` have older releases which pin incompatible `grpc-google-iam-v1`.

```bash
$ for f in */setup.py; do if grep -q grpc-google-iam-v1 $f; then grep -q grpc-google-iam-v1 `dirname $f`/CHANGELOG.md || echo $f; fi; done
bigtable/setup.py
container/setup.py
```

PR #8830 fixes this issue.

**Comment by tseaver** [comment] 2019-07-30 17:52
Closed via #8827, #8830.

**Comment by tseaver** [comment] 2019-07-30 17:53
@thrykol `google-cloud-spanner 1.10.0` was released last Thursday (2019-07-25).

**Closed by tseaver** 2019-07-30 17:52 UTC
Labels: api: bigtable, api: container, packaging, priority: p0, type: bug
