### ISSUE TITLE
Auto ML: ServiceUnavailable raised from 'predict'

### ISSUE THREAD

**Issue by Gunjitbedi** [googleapis/google-cloud-python#7996] opened 2019-05-16 11:00 UTC
#### Environment details
OS: Windows 10
Python 3.6.5 :: Anaconda, Inc.
Name: google-cloud-automl Version: 0.2.0

#### Steps to reproduce
I am working on 'AutoML Natural Language' and using it to prepare a custom text classification model. I have uploaded the data and trained it through the AutoML UI - "https://cloud.google.com/automl". Now, for predicting the results i am using the Python syntax. but it gives below error

google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed

#### Code example
```import sys

from google.cloud import automl_v1beta1

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="My First Project-ccf4469590bb.json"

def get_prediction(content, project_id, model_id):
      prediction_client = automl_v1beta1.PredictionServiceClient()
      name = 'projects/{}/locations/us-central1/models/{}'.format(project_id, model_id)
      payload = {'text_snippet': {'content': content, 'mime_type': 'text/plain'}}
      params = {}
      request = prediction_client.predict(name, payload, params)
      return request  # waits till request is returned

if __name__ == '__main__':
  content = sys.argv[1]
  project_id = sys.argv[2]
  model_id = sys.argv[3]

  print (get_prediction(content, project_id,  model_id))

Command line : C:\Users\gunjit.bedi\Desktop\Python\OPENML>python Code.py "My issue was resolved" dogwood-baton-240611 TCN5526896291447140535

```
#### Stack trace
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\grpc\_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connect Failed"
        debug_error_string = "{"created":"@1558002094.368000000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2608,"referenced_errors":[{"created":"@1558002094.368000000","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":234,"referenced_errors":[{"created":"@1558002094.368000000","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1558002094.368000000","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":321,"referenced_errors":[{"created":"@1558002094.368000000","description":"An attempt was made to access a socket in a way forbidden by its access permissions.\r\n","file":"src/core/lib/iomgr/tcp_windows.cc","file_line":190}]}]}]}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Code.py", line 27, in <module>
    print (get_prediction(content, project_id,  model_id))
  File "Code.py", line 19, in get_prediction
    request = prediction_client.predict(name, payload, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\cloud\automl_v1beta1\gapic\prediction_service_client.py", line 311, in predict
    request, retry=retry, timeout=timeout, metadata=metadata
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\gapic_v1\method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\retry.py", line 179, in retry_target
    return target()
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed
```

**Comment by tseaver** [comment] 2019-05-16 16:43
@beccasaurus Are there any known issues with the Auto ML API which would explain this issue?  The GAPIC `Predict` method is marked as `non_idempotent`, which means that we don't automatically retry for 503 responses.

**Comment by nnegrey** [comment] 2019-12-10 17:45
The API has no gone, GA, but I've been unable to reproduce this and haven't seen this behavior on beta or v1 endpoints. Going to close this out unless you are still having issues.

**Closed by nnegrey** 2019-12-10 17:45 UTC
Labels: api: automl, backend, type: question
