### ISSUE TITLE
BigQuery Data Transfer: 'list_transfer_configs' returns empty object.

### ISSUE THREAD

**Issue by meisam91** [googleapis/google-cloud-python#8466] opened 2019-06-22 13:44 UTC
It looks like there's an issue with the bigquery_datatransfer API not returning the list of transfers:

`print list(client.list_transfer_configs(parent="projects/{project_id}", data_source_ids="scheduled_query"))`

output is:
`[]`

**Comment by tseaver** [comment] 2019-06-24 16:05
[`DataTransferServiceClient.list_transfer_configs`](https://github.com/googleapis/google-cloud-python/blob/f278f3fbacbb9b9c6593a5d12a56b0579c5b78f6/bigquery_datatransfer/google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py#L744-L848) is a generated wrapper around the gRPC [`projects.locations.transferConfigs.list` API call](https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs/list).  I would be very surprised if it was not returning exactly what the API does.

Can you please try the call against your project in the API Explorer in those docs?

**Comment by meisam91** [comment] 2019-06-24 16:24
I’ve actually done that today and found out that parent is actually in the format of “projects/example-project-is/locations/europe” 

Although this did produce the expected results in the api explorer, in the python library it still is outputting an empty object

**Comment by tseaver** [comment] 2019-06-24 16:29
@tswast Can you point us in the right direction here?

**Comment by meisam91** [comment] 2019-06-25 08:59
Just to add further, for continuity purposes, in my code, I've gone ahead and directly accessed the API - this works as expected:

`from google.auth.transport.requests import AuthorizedSession
import google.auth

credentials, project = google.auth.default()
authed_session = AuthorizedSession(credentials)

response = authed_session.request('GET','https://bigquerydatatransfer.googleapis.com/v1/projects/example-project-id/locations/europe/transferConfigs', params={'dataSourceIds': 'scheduled_query'})

print response.text`

**Comment by meisam91** [comment] 2019-06-27 11:36
Any updates on this issue?

**Comment by tswast** [comment] 2019-07-08 22:11
@meisam91 Are you using a service account or user-based credentials? With service account credentials, there's a known issue on the backend where no transfer configs are listed.

**Comment by meisam91** [comment] 2019-07-08 23:25
@tswast I was using the default service account assigned to cloud functions / cloud shell. 

Do we have any idea on when this backend issue would be fixed? Could you point me to the ticket created around the backend issue so I can keep tabs on it?

Thanks a lot!

**Comment by tswast** [comment] 2019-11-22 22:49
I tried this again with the following code sample, and determined it doesn't have to do with the credentials that are used. It happens with both service account and user credentials.

```python
from google.cloud import bigquery_datatransfer_v1


client = bigquery_datatransfer_v1.DataTransferServiceClient()
project_id = "my-project"
print(list(client.list_transfer_configs(
    parent=f"projects/{project_id}",
    data_source_ids="scheduled_query",
)))
client.transport.channel.close()


import google_auth_oauthlib


credentials = google_auth_oauthlib.get_user_credentials(
    ["https://www.googleapis.com/auth/cloud-platform"],
    client_id="1234567890.apps.googleusercontent.com",
    client_secret="ABCDEFG",
)
client = bigquery_datatransfer_v1.DataTransferServiceClient(
    credentials=credentials,
)
print(list(client.list_transfer_configs(
    parent=f"projects/{project_id}",
    data_source_ids="scheduled_query",
))
```

**Comment by tswast** [comment] 2019-11-22 22:52
I think the problem is that `data_source_ids` needs to be a list of strings.

```python
print(list(client.list_transfer_configs(
    parent=f"projects/{project_id}",
    data_source_ids=["scheduled_query"],
))
```

Outputs:

```
[name: "projects/769108155013/locations/us/transferConfigs/5ce7c0fb-0000-21e1-b910-089e08325a74"
 destination_dataset_id: "your_dataset_id"
 display_name: "Your Scheduled Query Name"
 update_time {
   seconds: 1555445167
   nanos: 381137000
 }
 data_source_id: "scheduled_query"
 schedule: "every 24 hours"
 next_run_time {
   seconds: 1574539560
 }
 params {
   fields {
     key: "destination_table_name_template"
     value {
       string_value: "your_table_{run_date}"
     }
   }
   fields {
     key: "partitioning_field"
     value {
       string_value: ""
     }
   }
   fields {
     key: "query"
     value {
       string_value: "SELECT 1;  -- Use standard SQL syntax."
     }
   }
   fields {
     key: "write_disposition"
     value {
       string_value: "WRITE_TRUNCATE"
     }
   }
 }
 state: SUCCEEDED
 user_id: 7474305991939193967
 dataset_region: "us",
 name: "projects/769108155013/locations/us/transferConfigs/5cec26f7-0000-247d-b388-f403045f2370"
 destination_dataset_id: "your_dataset_id"
 display_name: "Your Scheduled Query Name"
 update_time {
   seconds: 1558546156
   nanos: 745354000
 }
 data_source_id: "scheduled_query"
 schedule: "every 24 hours"
 next_run_time {
   seconds: 1574530140
 }
 params {
   fields {
     key: "destination_table_name_template"
     value {
       string_value: "your_table_{run_date}"
     }
   }
   fields {
     key: "partitioning_field"
     value {
       string_value: ""
     }
   }
   fields {
     key: "query"
     value {
       string_value: "SELECT 1;  -- Use standard SQL syntax."
     }
   }
   fields {
     key: "write_disposition"
     value {
       string_value: "WRITE_TRUNCATE"
     }
   }
 }
 state: SUCCEEDED
 user_id: 2870224704673701825
 dataset_region: "us",
 name: "projects/769108155013/locations/us/transferConfigs/5d058146-0000-2f31-9ee8-883d24fedd44"
 destination_dataset_id: "your_dataset_id"
 display_name: "Your Scheduled Query Name"
 update_time {
   seconds: 1555445554
   nanos: 969391000
 }
 data_source_id: "scheduled_query"
 schedule: "every 24 hours"
 next_run_time {
   seconds: 1574539920
 }
 params {
   fields {
     key: "destination_table_name_template"
     value {
       string_value: "your_table_{run_date}"
     }
   }
   fields {
     key: "partitioning_field"
     value {
       string_value: ""
     }
   }
   fields {
     key: "query"
     value {
       string_value: "SELECT 1;  -- Use standard SQL syntax."
     }
   }
   fields {
     key: "write_disposition"
     value {
       string_value: "WRITE_TRUNCATE"
     }
   }
 }
 state: SUCCEEDED
 user_id: 7474305991939193967
 dataset_region: "us",
 name: "projects/769108155013/locations/us/transferConfigs/5d1d052f-0000-2c65-a1eb-089e0825e5e0"
 destination_dataset_id: "your_dataset_id"
 display_name: "Your Scheduled Query Name"
 update_time {
   seconds: 1560800932
   nanos: 634091000
 }
 data_source_id: "scheduled_query"
 schedule: "every 24 hours"
 next_run_time {
   seconds: 1574538480
 }
 params {
   fields {
     key: "destination_table_name_template"
     value {
       string_value: "your_table_{run_date}"
     }
   }
   fields {
     key: "partitioning_field"
     value {
       string_value: ""
     }
   }
   fields {
     key: "query"
     value {
       string_value: "SELECT 1;  -- Use standard SQL syntax."
     }
   }
   fields {
     key: "write_disposition"
     value {
       string_value: "WRITE_TRUNCATE"
     }
   }
 }
 state: SUCCEEDED
 user_id: 2870224704673701825
 dataset_region: "us"]
```

I'll update the internal issue to ask the backend team if they can return an error when a string is sent instead of a list of strings.

**Comment by tswast** [comment] 2020-01-08 22:23
Closing, as I believe the customer issue is resolved (use list of strings, not a string).

**Closed by tswast** 2020-01-08 22:23 UTC
Labels: api: bigquerydatatransfer, type: question

**Comment by NicolaSpreafico** [comment] 2020-04-07 12:03
Hi, same issue. I'm using authentication with service_account and method returns empty

```
		client = bigquery_datatransfer_v1.DataTransferServiceClient(credentials=self._credentials)
		parent = client.project_path(self._project_id)
		print(list(client.list_transfer_configs(
			parent=parent,
			data_source_ids=["scheduled_query"]
		)))
```

Output is
```
[]
```

**Comment by NicolaSpreafico** [comment] 2020-04-08 06:16
If anyone is having the same problem, with region EU, please mind this reply from Google support:

> It’s important to note that the ‘transferConfigs.list’ API [1] method accepts a 'parent' identifier in the following form: projects/{project_id}/locations/<your_datataset_location_here>.
> 
> If you only specify a parent in the form projects/{project_id} (as in your code), this request will **default to the US location**. Since all of your datasets are in **location EU, you'd need to explicitly set location** in the parent as follows: projects/{project_id}/locations/eu. Similarly, your code would define the parent string in the following way: parent=f"projects/{project_id}/locations/eu"

[1] https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs/list
